-- migrations/010_lexestate.sql
-- LexEstate: Real Estate English Vocabulary Platform

-- ─── Tables ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lexestate_categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  description TEXT,
  icon        TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lexestate_terms (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  word_en         TEXT NOT NULL,
  translation_es  TEXT NOT NULL,
  definition_en   TEXT NOT NULL,
  definition_es   TEXT NOT NULL,
  pronunciation   TEXT,
  ipa             TEXT,
  audio_url       TEXT,
  image_url       TEXT,
  video_url       TEXT,
  example_en      TEXT,
  example_es      TEXT,
  level           TEXT NOT NULL CHECK (level IN ('A1','A2','B1','B2','C1','C2')),
  category_id     UUID REFERENCES lexestate_categories(id) ON DELETE SET NULL,
  synonyms        TEXT[],
  related_terms   TEXT[],
  common_mistakes TEXT,
  notes           TEXT,
  difficulty      INTEGER CHECK (difficulty BETWEEN 1 AND 5) DEFAULT 3,
  frequency       INTEGER CHECK (frequency BETWEEN 1 AND 5) DEFAULT 3,
  tags            TEXT[],
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lexestate_practice_questions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  term_id        UUID REFERENCES lexestate_terms(id) ON DELETE CASCADE,
  category_id    UUID REFERENCES lexestate_categories(id) ON DELETE SET NULL,
  level          TEXT,
  question_type  TEXT NOT NULL CHECK (question_type IN (
    'definition_es_to_word','definition_en_to_word','word_to_definition_es',
    'word_to_translation_es','example_gap_to_word','audio_to_word')),
  question_text  TEXT NOT NULL,
  correct_answer TEXT NOT NULL,
  options        JSONB NOT NULL DEFAULT '[]',
  explanation    TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lexestate_favorites (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    TEXT NOT NULL,
  term_id    UUID NOT NULL REFERENCES lexestate_terms(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, term_id)
);

CREATE TABLE IF NOT EXISTS lexestate_user_progress (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          TEXT NOT NULL,
  term_id          UUID NOT NULL REFERENCES lexestate_terms(id) ON DELETE CASCADE,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','learning','difficult','mastered')),
  correct_answers  INTEGER DEFAULT 0,
  wrong_answers    INTEGER DEFAULT 0,
  attempts         INTEGER DEFAULT 0,
  correct_streak   INTEGER DEFAULT 0,
  last_reviewed_at TIMESTAMPTZ,
  next_review_at   TIMESTAMPTZ,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, term_id)
);

CREATE TABLE IF NOT EXISTS lexestate_review_history (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        TEXT NOT NULL,
  term_id        UUID REFERENCES lexestate_terms(id) ON DELETE CASCADE,
  exercise_type  TEXT,
  question_type  TEXT,
  user_answer    TEXT,
  correct_answer TEXT,
  is_correct     BOOLEAN NOT NULL,
  reviewed_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lexestate_quiz_results (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         TEXT NOT NULL,
  score           INTEGER NOT NULL,
  total_questions INTEGER NOT NULL,
  percentage      NUMERIC(5,2) NOT NULL,
  category_id     UUID REFERENCES lexestate_categories(id) ON DELETE SET NULL,
  level           TEXT,
  question_type   TEXT,
  time_seconds    INTEGER DEFAULT 0,
  mistakes        JSONB DEFAULT '[]',
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lexestate_settings (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            TEXT NOT NULL UNIQUE,
  theme              TEXT DEFAULT 'dark',
  language           TEXT DEFAULT 'es',
  audio_speed        NUMERIC DEFAULT 1.0,
  auto_pronunciation BOOLEAN DEFAULT FALSE,
  daily_goal         INTEGER DEFAULT 10,
  weekly_goal        INTEGER DEFAULT 50,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Indexes ────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_lex_terms_category  ON lexestate_terms(category_id);
CREATE INDEX IF NOT EXISTS idx_lex_terms_level     ON lexestate_terms(level);
CREATE INDEX IF NOT EXISTS idx_lex_progress_user   ON lexestate_user_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_lex_review_user     ON lexestate_review_history(user_id);
CREATE INDEX IF NOT EXISTS idx_lex_favorites_user  ON lexestate_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_lex_quiz_user       ON lexestate_quiz_results(user_id);

-- ─── RLS ────────────────────────────────────────────────────────────────────────
ALTER TABLE lexestate_categories         ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_terms              ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_practice_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_favorites          ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_user_progress      ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_review_history     ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_quiz_results       ENABLE ROW LEVEL SECURITY;
ALTER TABLE lexestate_settings           ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lex_categories_public_read" ON lexestate_categories FOR SELECT USING (true);
CREATE POLICY "lex_terms_public_read"      ON lexestate_terms      FOR SELECT USING (true);
CREATE POLICY "lex_questions_public_read"  ON lexestate_practice_questions FOR SELECT USING (true);

-- User-specific tables: all writes go through service key on the server
-- These policies protect against direct client access
CREATE POLICY "lex_favorites_own"  ON lexestate_favorites       FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "lex_progress_own"   ON lexestate_user_progress   FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "lex_review_own"     ON lexestate_review_history  FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "lex_quiz_own"       ON lexestate_quiz_results    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "lex_settings_own"   ON lexestate_settings        FOR ALL USING (true) WITH CHECK (true);

-- ─── Seed: Categories ──────────────────────────────────────────────────────────
INSERT INTO lexestate_categories (name, slug, description, icon) VALUES
('Sales',              'sales',               'Property buying and selling terminology',        '🏠'),
('Rentals',            'rentals',             'Leasing and rental market vocabulary',           '🔑'),
('Construction',       'construction',        'Building and development terms',                 '🏗️'),
('Architecture',       'architecture',        'Design, layout and structural concepts',         '📐'),
('Investment',         'investment',          'Real estate investment and returns',              '📈'),
('Finance',            'finance',             'Mortgages, loans and financial instruments',     '💰'),
('Legal',              'legal',               'Contracts, ownership and legal processes',       '⚖️'),
('Urban Planning',     'urban-planning',      'Zoning, land use and city development',          '🏙️'),
('Property Management','property-management', 'Managing rental portfolios and tenants',         '🏢'),
('Marketing',          'marketing',           'Listing, presenting and promoting properties',   '📣'),
('Luxury',             'luxury',              'High-end and premium property vocabulary',       '✨'),
('Commercial',         'commercial',          'Offices, retail and commercial spaces',          '🏪'),
('Hospitality',        'hospitality',         'Hotels, holiday lets and tourism property',      '🏨'),
('PropTech',           'proptech',            'Technology and digital tools in real estate',    '💻')
ON CONFLICT (slug) DO NOTHING;

-- ─── Seed: Terms ───────────────────────────────────────────────────────────────
INSERT INTO lexestate_terms
  (word_en, translation_es, definition_en, definition_es, pronunciation, ipa,
   example_en, example_es, level, category_id, synonyms, related_terms,
   common_mistakes, difficulty, frequency, tags)
VALUES

-- SALES
('property','propiedad / inmueble',
 'A building or area of land that is owned by someone.',
 'Edificio o terreno que pertenece a alguien.',
 'PROP-er-tee','/ˈprɒpəti/',
 'The property has three bedrooms and a large garden.',
 'La propiedad tiene tres dormitorios y un gran jardín.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['real estate','asset'],ARRAY['land','building','estate'],
 'No confundir con "propriety" (decoro).',1,5,ARRAY['basic','fundamental']),

('real estate','bienes raíces / sector inmobiliario',
 'Land, buildings and other property, or the business of buying and selling them.',
 'Terrenos, edificios y otras propiedades, o el negocio de comprarlos y venderlos.',
 'REEL ih-STATE','/riːl ɪˈsteɪt/',
 'She has worked in real estate for over ten years.',
 'Lleva más de diez años en el sector inmobiliario.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['property','realty'],ARRAY['property market','agent','broker'],
 'En UK se dice más "property" que "real estate".',1,5,ARRAY['basic','industry']),

('listing','anuncio / oferta de venta',
 'A property that is registered with an estate agent for sale or rent.',
 'Propiedad registrada con un agente inmobiliario para su venta o alquiler.',
 'LIS-ting','/ˈlɪstɪŋ/',
 'The new listing attracted over fifty enquiries in the first week.',
 'El nuevo anuncio atrajo más de cincuenta consultas en la primera semana.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['advertisement','entry'],ARRAY['MLS','portal','agent'],
 'No confundir con "list" (lista).',2,5,ARRAY['marketing','portal']),

('buyer','comprador',
 'A person or company that is buying something, especially a property.',
 'Persona o empresa que está comprando algo, especialmente una propiedad.',
 'BY-er','/ˈbaɪər/',
 'The buyer made an offer below the asking price.',
 'El comprador hizo una oferta por debajo del precio de venta.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['purchaser','acquirer'],ARRAY['seller','offer','transaction'],
 NULL,1,5,ARRAY['basic','role']),

('seller','vendedor',
 'A person who sells something, especially a property.',
 'Persona que vende algo, especialmente una propiedad.',
 'SEL-er','/ˈsɛlər/',
 'The seller accepted the offer after a short negotiation.',
 'El vendedor aceptó la oferta tras una breve negociación.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['vendor','owner'],ARRAY['buyer','transaction','price'],
 'En UK inmobiliario se prefiere "vendor".',1,5,ARRAY['basic','role']),

('viewing','visita comercial',
 'An arranged visit to a property that is for sale or rent.',
 'Visita acordada a una propiedad en venta o alquiler.',
 'VYOO-ing','/ˈvjuːɪŋ/',
 'We have scheduled three viewings for Saturday morning.',
 'Hemos programado tres visitas para el sábado por la mañana.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['showing','visit'],ARRAY['appointment','offer','lead'],
 NULL,2,5,ARRAY['sales-process','appointment']),

('offer','oferta',
 'A formal proposal to buy a property at a stated price.',
 'Propuesta formal para comprar una propiedad a un precio determinado.',
 'OF-er','/ˈɒfər/',
 'They put in an offer of £350,000 for the house.',
 'Hicieron una oferta de 350.000 £ por la casa.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['bid','proposal'],ARRAY['counteroffer','acceptance','negotiation'],
 NULL,1,5,ARRAY['negotiation','price']),

('counteroffer','contraoferta',
 'A response to an offer in which a different price or conditions are proposed.',
 'Respuesta a una oferta en la que se propone un precio o condiciones diferentes.',
 'COWN-ter-of-er','/ˈkaʊntərˌɒfər/',
 'The seller rejected the bid and submitted a counteroffer at a higher price.',
 'El vendedor rechazó la oferta y presentó una contraoferta a un precio superior.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['counter-proposal','revised offer'],ARRAY['offer','negotiation'],
 NULL,3,4,ARRAY['negotiation']),

('closing','cierre / firma',
 'The final step in a property transaction where ownership is legally transferred.',
 'Último paso en una transacción inmobiliaria donde la propiedad cambia de dueño.',
 'KLOH-zing','/ˈkləʊzɪŋ/',
 'The closing took place at the notary office last Thursday.',
 'El cierre tuvo lugar en la notaría el jueves pasado.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['completion','settlement'],ARRAY['conveyancing','deed','notary'],
 NULL,3,5,ARRAY['transaction','final-step']),

('off-plan property','propiedad sobre plano',
 'A property sold before it has been built, based on architectural plans.',
 'Propiedad vendida antes de ser construida, basándose en planos arquitectónicos.',
 'off-PLAN','/ˌɒf ˈplæn/',
 'Buying off-plan can offer significant savings compared to completed properties.',
 'Comprar sobre plano puede ofrecer ahorros significativos frente a propiedades terminadas.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['pre-construction','pre-built'],ARRAY['new build','developer','completion date'],
 NULL,4,4,ARRAY['development','new-build','risk']),

('resale property','propiedad de segunda mano',
 'A property that has been previously owned and is being sold again.',
 'Propiedad que ha tenido propietario anterior y se vuelve a poner en venta.',
 're-SALE','/ˌriːˈseɪl/',
 'The resale property was priced below market value due to its condition.',
 'La propiedad de segunda mano tenía un precio por debajo del mercado por su estado.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['second-hand property','existing home'],ARRAY['new build','renovation'],
 NULL,2,4,ARRAY['existing','second-hand']),

('home staging','preparación del inmueble para la venta',
 'The practice of preparing and decorating a property to make it more attractive to buyers.',
 'Práctica de preparar y decorar una propiedad para hacerla más atractiva a compradores.',
 'HOME STAY-jing','/həʊm ˈsteɪdʒɪŋ/',
 'Professional home staging increased the sale price by 8%.',
 'El home staging profesional aumentó el precio de venta un 8%.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['property styling','presentation'],ARRAY['photography','listing','marketing'],
 NULL,3,3,ARRAY['marketing','presentation']),

('lead','contacto potencial',
 'A potential customer who has shown interest in buying or renting a property.',
 'Potencial cliente que ha mostrado interés en comprar o alquilar una propiedad.',
 'LEED','/liːd/',
 'The agency generated 40 new leads from the online portal last month.',
 'La agencia generó 40 nuevos contactos del portal online el mes pasado.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['prospect','enquiry','contact'],ARRAY['CRM','conversion','pipeline'],
 NULL,2,4,ARRAY['sales','crm']),

('new build','obra nueva',
 'A property that has just been built and has never been lived in before.',
 'Propiedad recién construida en la que nadie ha vivido anteriormente.',
 'NEW BILD','/njuː bɪld/',
 'The new build development offers 50 apartments with energy-efficient design.',
 'La promoción de obra nueva ofrece 50 apartamentos con diseño eficiente.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['newly built','brand new'],ARRAY['off-plan','developer','warranty'],
 NULL,1,5,ARRAY['development','construction']),

-- RENTALS
('tenant','inquilino / arrendatario',
 'A person who pays rent to live in or use a property owned by someone else.',
 'Persona que paga alquiler para vivir o usar una propiedad de otro.',
 'TEN-ant','/ˈtɛnənt/',
 'The tenant must give one month''s notice before leaving.',
 'El inquilino debe avisar con un mes de antelación antes de marcharse.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['renter','lessee','occupant'],ARRAY['landlord','lease','rent'],
 'No confundir con "renter" (EEUU) o "occupier" (legal UK).',1,5,ARRAY['rental','role']),

('landlord','propietario arrendador',
 'A person or company that owns property and rents it out to tenants.',
 'Persona o empresa que posee una propiedad y la alquila a inquilinos.',
 'LAND-lord','/ˈlændlɔːd/',
 'The landlord is responsible for maintaining the heating system.',
 'El propietario es responsable de mantener el sistema de calefacción.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['owner','lessor','property owner'],ARRAY['tenant','lease','maintenance'],
 NULL,1,5,ARRAY['rental','role']),

('lease','contrato de arrendamiento',
 'A legal agreement to rent a property for a specified period.',
 'Acuerdo legal para alquilar una propiedad por un período específico.',
 'LEES','/liːs/',
 'The lease runs for 12 months and can be renewed annually.',
 'El contrato dura 12 meses y se puede renovar anualmente.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['rental contract','tenancy agreement'],ARRAY['landlord','tenant','renewal'],
 'En UK "tenancy agreement" es más habitual; "lease" suele referirse a comerciales.',2,5,ARRAY['contract','legal']),

('rental agreement','contrato de alquiler',
 'A contract between landlord and tenant specifying rent, duration and conditions.',
 'Contrato entre propietario e inquilino que especifica el alquiler, duración y condiciones.',
 'REN-tal a-GREE-ment','/ˈrɛntəl əˈɡriːmənt/',
 'Both parties signed the rental agreement before the tenant moved in.',
 'Ambas partes firmaron el contrato de alquiler antes de que el inquilino entrara.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['lease','tenancy agreement'],ARRAY['landlord','tenant','deposit'],
 NULL,2,5,ARRAY['contract','legal']),

('deposit','fianza / depósito de garantía',
 'A sum of money paid at the start of a tenancy as security against damage or unpaid rent.',
 'Suma de dinero pagada al inicio del arrendamiento como garantía frente a daños o impagos.',
 'deh-POZ-it','/dɪˈpɒzɪt/',
 'A deposit equivalent to two months'' rent is required to secure the flat.',
 'Se requiere una fianza equivalente a dos meses de alquiler para asegurar el piso.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['security deposit','bond'],ARRAY['tenant','lease','rental agreement'],
 '"Deposit" en compra = señal/arras; en alquiler = fianza. El contexto es clave.',1,5,ARRAY['rental','finance']),

('vacancy','unidad desocupada',
 'A property that is empty and currently available for rent or purchase.',
 'Propiedad que está vacía y actualmente disponible para alquiler o compra.',
 'VAY-kan-see','/ˈveɪkənsi/',
 'The building currently has three vacancies on the upper floors.',
 'El edificio tiene actualmente tres unidades desocupadas en los pisos superiores.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['empty unit','void'],ARRAY['occupancy rate','landlord','income'],
 NULL,2,3,ARRAY['rental','occupancy']),

('subletting','subarrendamiento',
 'The practice of a tenant renting out all or part of their property to a third party.',
 'Práctica de un inquilino que alquila a un tercero toda o parte de su propiedad arrendada.',
 'SUB-let-ing','/ˈsʌblɛtɪŋ/',
 'Subletting is prohibited without the landlord''s written consent.',
 'El subarrendamiento está prohibido sin el consentimiento escrito del propietario.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['sublease','sub-rent'],ARRAY['tenant','lease','permission'],
 NULL,3,3,ARRAY['rental','legal']),

('eviction','desahucio / desalojo',
 'The legal process of removing a tenant from a property.',
 'Proceso legal para desalojar a un inquilino de una propiedad.',
 'ee-VIK-shun','/ɪˈvɪkʃən/',
 'The landlord obtained an eviction order after six months of unpaid rent.',
 'El propietario obtuvo una orden de desahucio tras seis meses de impago.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='rentals'),
 ARRAY['repossession','eviction order'],ARRAY['landlord','court','arrears'],
 NULL,4,3,ARRAY['legal','rental']),

-- FINANCE
('mortgage','hipoteca',
 'A loan secured against a property, used to finance its purchase.',
 'Préstamo garantizado con una propiedad, utilizado para financiar su compra.',
 'MOR-gij','/ˈmɔːɡɪdʒ/',
 'They took out a 25-year mortgage to finance the purchase.',
 'Pidieron una hipoteca a 25 años para financiar la compra.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['home loan','housing loan'],ARRAY['interest rate','lender','repayment'],
 'La "t" es muda: se pronuncia "MOR-gij".',2,5,ARRAY['finance','loan']),

('appraisal','tasación',
 'A professional assessment of the market value of a property by a certified expert.',
 'Evaluación profesional del valor de mercado de una propiedad por un experto certificado.',
 'a-PRAY-zal','/əˈpreɪzəl/',
 'The bank required an independent appraisal before approving the mortgage.',
 'El banco exigió una tasación independiente antes de aprobar la hipoteca.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['valuation','assessment'],ARRAY['mortgage','market value','surveyor'],
 'En UK se usa más "valuation"; "appraisal" es más americano.',3,4,ARRAY['finance','valuation']),

('valuation','valoración',
 'The process of estimating the monetary value of a property.',
 'Proceso para estimar el valor monetario de una propiedad.',
 'val-yoo-AY-shun','/ˌvæljuˈeɪʃən/',
 'The estate agent provided a free valuation of the property.',
 'El agente inmobiliario realizó una valoración gratuita de la propiedad.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['appraisal','assessment'],ARRAY['market value','mortgage','appraisal'],
 NULL,2,4,ARRAY['finance','british']),

('title deed','escritura de propiedad',
 'A legal document proving who owns a property.',
 'Documento legal que acredita quién es el propietario de un bien inmueble.',
 'TY-tel DEED','/ˈtaɪtəl diːd/',
 'The solicitor checked the title deed to confirm there were no encumbrances.',
 'El abogado revisó la escritura para confirmar que no había cargas.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['deed of ownership','property document'],ARRAY['land registry','conveyancing','notary'],
 NULL,3,4,ARRAY['legal','ownership']),

('land registry','registro de la propiedad',
 'An official government register recording land and property ownership.',
 'Registro oficial del gobierno que recoge la propiedad de terrenos e inmuebles.',
 'LAND REJ-is-tree','/lænd ˈrɛdʒɪstri/',
 'The buyer registered the title at the Land Registry after completion.',
 'El comprador inscribió la escritura en el Registro de la Propiedad tras el cierre.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['property register','cadastre'],ARRAY['title deed','conveyancing','ownership'],
 NULL,3,4,ARRAY['legal','official']),

('capital gain','plusvalía',
 'The profit made when selling an asset for more than it cost to buy.',
 'Ganancia obtenida al vender un activo por más de lo que costó comprarlo.',
 'KAP-i-tal GAYN','/ˈkæpɪtəl ɡeɪn/',
 'After selling the flat, they made a capital gain of €40,000.',
 'Tras vender el piso, obtuvieron una plusvalía de 40.000 €.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['profit','appreciation'],ARRAY['capital gains tax','investment','return'],
 NULL,3,4,ARRAY['finance','investment','tax']),

('return on investment','rentabilidad de la inversión',
 'The financial gain from an investment expressed as a percentage of its cost.',
 'Ganancia financiera de una inversión expresada como porcentaje de su coste.',
 'ree-TURN on in-VEST-ment','/rɪˈtɜːn ɒn ɪnˈvɛstmənt/',
 'The property delivered a return on investment of 12% in the first year.',
 'La propiedad ofreció una rentabilidad del 12% el primer año.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['ROI','profitability'],ARRAY['yield','capital gain','investment'],
 'Se usa la abreviatura ROI constantemente en el sector.',3,5,ARRAY['investment','roi','profitability']),

('down payment','entrada / pago inicial',
 'An upfront partial payment made when purchasing a property.',
 'Pago parcial inicial realizado al comprar una propiedad.',
 'DOWN PAY-ment','/daʊn ˈpeɪmənt/',
 'They saved for five years to afford the 20% down payment.',
 'Ahorraron cinco años para poder pagar la entrada del 20%.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['initial payment','deposit','earnest money'],ARRAY['mortgage','loan','purchase'],
 NULL,2,4,ARRAY['finance','purchase','american']),

('equity','capital propio / patrimonio neto',
 'The value of a property minus any outstanding mortgage or loans.',
 'Valor de una propiedad menos la hipoteca u otros préstamos pendientes.',
 'EK-wi-tee','/ˈɛkwɪti/',
 'After ten years of mortgage payments, they had built up significant equity.',
 'Tras diez años de hipoteca, habían acumulado un patrimonio neto significativo.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['net worth','ownership stake'],ARRAY['mortgage','loan-to-value','remortgage'],
 'No confundir "equity" financiero con "equity" como justicia.',3,4,ARRAY['finance','ownership']),

('foreclosure','ejecución hipotecaria',
 'The legal process by which a lender repossesses a property when the borrower defaults.',
 'Proceso legal por el que un prestamista recupera una propiedad cuando el prestatario incumple.',
 'for-KLOH-zhur','/fɔːˈkləʊʒər/',
 'The bank initiated foreclosure proceedings after 90 days of missed payments.',
 'El banco inició el proceso de ejecución hipotecaria tras 90 días sin pago.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['repossession','default'],ARRAY['mortgage','default','lender'],
 'En UK se dice "repossession"; "foreclosure" es término americano.',4,3,ARRAY['legal','finance']),

('escrow','depósito en garantía',
 'An arrangement where a third party holds funds during a transaction until conditions are met.',
 'Mecanismo por el que un tercero retiene fondos durante una transacción hasta que se cumplan las condiciones.',
 'ES-kroh','/ˈɛskrəʊ/',
 'The deposit was held in escrow until the sale was completed.',
 'El depósito se retuvo en garantía hasta que se completó la venta.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['trust account','held funds'],ARRAY['closing','deposit','conveyancing'],
 NULL,4,3,ARRAY['legal','finance','american']),

('amortization','amortización',
 'The gradual repayment of a loan through regular instalments of principal and interest.',
 'Devolución gradual de un préstamo mediante cuotas regulares de capital e intereses.',
 'a-mor-ti-ZAY-shun','/əˌmɔːtɪˈzeɪʃən/',
 'The mortgage amortization schedule showed how interest costs decrease over time.',
 'El cuadro de amortización de la hipoteca mostraba cómo disminuyen los intereses con el tiempo.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['repayment','loan payment'],ARRAY['mortgage','instalment','interest'],
 NULL,4,4,ARRAY['finance','loan']),

('interest rate','tipo de interés',
 'The percentage charged by a lender on the amount borrowed.',
 'Porcentaje que cobra un prestamista sobre el capital prestado.',
 'IN-ter-est RAYT','/ˈɪntrəst reɪt/',
 'Rising interest rates increased monthly mortgage payments significantly.',
 'La subida del tipo de interés aumentó considerablemente las cuotas hipotecarias.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['rate','borrowing rate'],ARRAY['mortgage','fixed rate','variable rate'],
 NULL,2,5,ARRAY['finance','mortgage','economics']),

('fixed rate','tipo fijo',
 'A mortgage or loan where the interest rate stays the same for a set period.',
 'Hipoteca o préstamo donde el tipo de interés permanece igual durante un período fijo.',
 'FIKST RAYT','/fɪkst reɪt/',
 'They chose a five-year fixed rate mortgage for financial security.',
 'Eligieron una hipoteca a tipo fijo de cinco años por seguridad financiera.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['fixed interest','fixed mortgage'],ARRAY['variable rate','mortgage','repayment'],
 NULL,2,4,ARRAY['finance','mortgage']),

('variable rate','tipo variable',
 'A mortgage where the interest rate can change over time, usually linked to a base rate.',
 'Hipoteca donde el tipo de interés puede cambiar con el tiempo, normalmente ligado a un tipo de referencia.',
 'VAIR-ee-a-bul RAYT','/ˈveəriəbl reɪt/',
 'A variable rate mortgage can save money when interest rates fall.',
 'Una hipoteca a tipo variable puede ahorrar dinero cuando bajan los tipos.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['adjustable rate','floating rate'],ARRAY['fixed rate','mortgage','Euribor'],
 NULL,2,4,ARRAY['finance','mortgage']),

('refinancing','refinanciación',
 'Replacing an existing mortgage with a new one, usually to get better terms.',
 'Sustituir una hipoteca existente por una nueva, normalmente para obtener mejores condiciones.',
 'ree-FY-nan-sing','/ˌriːfaɪˈnænsɪŋ/',
 'Refinancing saved them €200 a month on their mortgage repayments.',
 'La refinanciación les ahorró 200 € al mes en las cuotas hipotecarias.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['remortgage','loan restructure'],ARRAY['mortgage','interest rate','equity'],
 NULL,3,3,ARRAY['finance','mortgage']),

-- CONSTRUCTION
('floor plan','plano de planta',
 'A scale diagram showing the layout of rooms in a property viewed from above.',
 'Diagrama a escala que muestra la distribución de habitaciones de una propiedad vista desde arriba.',
 'FLOR PLAN','/flɔː plæn/',
 'The floor plan showed an open-plan living area with three bedrooms.',
 'El plano de planta mostraba un salón diáfano con tres dormitorios.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['layout','blueprint'],ARRAY['built area','room','architect'],
 NULL,2,4,ARRAY['design','construction','measurement']),

('built area','superficie construida',
 'The total floor area of a building, including walls and shared spaces.',
 'Superficie total de un edificio, incluidos muros y zonas comunes.',
 'BILT AIR-ee-a','/bɪlt ˈeəriə/',
 'The apartment has a built area of 95 square metres.',
 'El apartamento tiene una superficie construida de 95 metros cuadrados.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['gross area','total floor area'],ARRAY['usable area','floor plan','square metres'],
 'Diferencia clave con "usable area": la construida incluye muros y zonas comunes.',3,4,ARRAY['measurement','area']),

('usable area','superficie útil',
 'The actual liveable floor space within a property, excluding walls and common areas.',
 'Espacio útil habitable real de una propiedad, sin incluir muros ni zonas comunes.',
 'YOO-za-bul AIR-ee-a','/ˈjuːzəbl ˈeəriə/',
 'The usable area is 78 square metres out of an 89 square metre built area.',
 'La superficie útil es de 78 m² de un total de 89 m² construidos.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['net floor area','habitable area'],ARRAY['built area','floor plan','square metres'],
 NULL,3,4,ARRAY['measurement','area']),

('plot','parcela / solar',
 'A piece of land intended for building or as part of a property.',
 'Terreno destinado para la construcción o como parte de una propiedad.',
 'PLOT','/plɒt/',
 'The plot measures 500 square metres and has planning permission.',
 'La parcela mide 500 metros cuadrados y tiene licencia de obras.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='urban-planning'),
 ARRAY['lot','land parcel','site'],ARRAY['zoning','building permit','land'],
 NULL,2,4,ARRAY['land','construction']),

('zoning','zonificación',
 'Legal regulations that define how land in specific areas can be used.',
 'Regulaciones legales que definen cómo puede utilizarse el suelo en zonas específicas.',
 'ZOH-ning','/ˈzəʊnɪŋ/',
 'The land is zoned for residential use, so commercial development is not permitted.',
 'El terreno está calificado para uso residencial, por lo que no se permite desarrollo comercial.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='urban-planning'),
 ARRAY['land classification','land use regulation'],ARRAY['building permit','plot','planning'],
 NULL,4,3,ARRAY['legal','planning','land-use']),

('building permit','licencia de obras',
 'Official permission from a local authority to construct or modify a building.',
 'Permiso oficial de una autoridad local para construir o modificar un edificio.',
 'BIL-ding PER-mit','/ˈbɪldɪŋ ˈpɜːmɪt/',
 'Construction cannot begin until the building permit has been approved.',
 'La construcción no puede comenzar hasta que se apruebe la licencia de obras.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['planning permission','construction permit'],ARRAY['zoning','architect','council'],
 NULL,3,4,ARRAY['legal','construction','planning']),

('completion date','fecha de entrega',
 'The agreed date on which a property purchase is finalised or a building is handed over.',
 'Fecha acordada en que se finaliza la compra de una propiedad o se entrega el edificio.',
 'kom-PLEE-shun DAYT','/kəmˈpliːʃən deɪt/',
 'The completion date is set for the 15th of March.',
 'La fecha de entrega está fijada para el 15 de marzo.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['handover date','closing date'],ARRAY['handover','contract','developer'],
 NULL,2,5,ARRAY['construction','transaction','schedule']),

('handover','entrega de llaves',
 'The transfer of a newly completed property from the developer to the buyer.',
 'Entrega de una propiedad recién terminada del promotor al comprador.',
 'HAND-oh-ver','/ˈhændˌəʊvər/',
 'The handover ceremony included a full inspection of the property.',
 'La entrega de llaves incluyó una inspección completa de la propiedad.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['delivery','key handover'],ARRAY['snagging list','completion date','developer'],
 NULL,2,4,ARRAY['construction','new-build']),

('snagging list','lista de defectos / acta de entrega',
 'A list of defects or unfinished work identified during inspection of a new build.',
 'Lista de defectos o trabajos incompletos identificados durante la inspección de una obra nueva.',
 'SNAG-ing LIST','/ˈsnæɡɪŋ lɪst/',
 'The buyer compiled a snagging list of 23 items before signing the handover document.',
 'El comprador elaboró una lista de 23 defectos antes de firmar el acta de entrega.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['defects list','punch list'],ARRAY['handover','new build','developer'],
 '"Punch list" es el término americano equivalente.',3,3,ARRAY['construction','inspection','quality']),

('renovation','reforma / renovación',
 'The process of improving or restoring a property to better condition.',
 'Proceso de mejorar o restaurar una propiedad a un estado mejor.',
 'ren-o-VAY-shun','/ˌrɛnəˈveɪʃən/',
 'The full renovation of the apartment took three months and cost €35,000.',
 'La reforma integral del apartamento tardó tres meses y costó 35.000 €.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['refurbishment','restoration','remodel'],ARRAY['building permit','contractor','value'],
 NULL,1,5,ARRAY['construction','improvement','value']),

('turnkey','llave en mano',
 'A property that is ready to occupy immediately, requiring no additional work.',
 'Propiedad lista para ocupar de inmediato, sin necesidad de ningún trabajo adicional.',
 'TURN-kee','/ˈtɜːnkiː/',
 'They bought a turnkey apartment and moved in the following week.',
 'Compraron un piso llave en mano y se mudaron la semana siguiente.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='construction'),
 ARRAY['move-in ready','ready to occupy'],ARRAY['new build','renovation','condition'],
 NULL,2,4,ARRAY['construction','condition','convenience']),

-- LEGAL
('conveyancing','transmisión inmobiliaria / gestión legal de compraventa',
 'The legal process of transferring property ownership from one person to another.',
 'Proceso legal de transferir la propiedad de un inmueble de una persona a otra.',
 'kon-VAY-an-sing','/kənˈveɪənsɪŋ/',
 'The conveyancing process took eight weeks from offer acceptance to completion.',
 'El proceso de transmisión tardó ocho semanas desde la aceptación de la oferta hasta el cierre.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['title transfer','property transfer'],ARRAY['solicitor','title deed','completion'],
 NULL,4,4,ARRAY['legal','process','british']),

('freehold','pleno dominio / propiedad absoluta',
 'Ownership of a property and the land it stands on, outright and indefinitely.',
 'Propiedad de un inmueble y el terreno en que se encuentra, de forma plena e indefinida.',
 'FREE-hold','/ˈfriːhəʊld/',
 'Buying freehold means you own the building and the land permanently.',
 'Comprar en pleno dominio significa ser propietario del edificio y del terreno de forma permanente.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['absolute ownership','fee simple'],ARRAY['leasehold','title deed','land registry'],
 'Concepto típicamente británico; el equivalente español es más próximo a "propiedad absoluta".',4,4,ARRAY['legal','ownership','british']),

('leasehold','arrendamiento de largo plazo',
 'Ownership of a property for a fixed number of years, not the land it stands on.',
 'Propiedad de un inmueble durante un número fijo de años, sin incluir el terreno.',
 'LEES-hold','/ˈliːshəʊld/',
 'Most flats in England are sold on a leasehold basis.',
 'La mayoría de pisos en Inglaterra se venden en régimen de arrendamiento de largo plazo.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['long lease'],ARRAY['freehold','ground rent','service charge'],
 'No confundir con "lease" (contrato de alquiler estándar).',4,4,ARRAY['legal','ownership','british']),

('due diligence','diligencia debida',
 'A thorough investigation of a property and its legal status before purchase.',
 'Investigación exhaustiva de una propiedad y su situación legal antes de la compra.',
 'dyoo DIL-i-jents','/djuː ˈdɪlɪdʒəns/',
 'The buyer''s solicitor carried out full due diligence before exchanging contracts.',
 'El abogado del comprador realizó una diligencia debida completa antes del intercambio de contratos.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['investigation','research','vetting'],ARRAY['survey','title deed','conveyancing'],
 NULL,4,4,ARRAY['legal','process']),

('deed','escritura pública',
 'A legal document that records the transfer of property ownership.',
 'Documento legal que registra la transmisión de la propiedad de un inmueble.',
 'DEED','/diːd/',
 'The deed was signed in the presence of a notary.',
 'La escritura fue firmada en presencia de un notario.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['title deed','conveyance deed'],ARRAY['notary','land registry','title'],
 NULL,3,4,ARRAY['legal','ownership']),

('easement','servidumbre',
 'The legal right to use another person''s land for a specific purpose.',
 'Derecho legal a utilizar el terreno de otra persona para un fin específico.',
 'EEZ-ment','/ˈiːzmənt/',
 'The neighbouring property has an easement allowing access across the driveway.',
 'La propiedad vecina tiene una servidumbre que permite el acceso a través de la entrada.',
 'C2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['right of way','servitude'],ARRAY['property rights','title','boundary'],
 NULL,5,2,ARRAY['legal','advanced']),

('co-ownership','copropiedad / proindiviso',
 'A situation where two or more people jointly own a property.',
 'Situación en que dos o más personas poseen conjuntamente una propiedad.',
 'koh-OH-ner-ship','/kəʊˈəʊnəʃɪp/',
 'The three siblings purchased the house in co-ownership after inheriting the funds.',
 'Los tres hermanos compraron la casa en copropiedad tras heredar el dinero.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['joint ownership','shared ownership'],ARRAY['deed','title','succession'],
 NULL,4,3,ARRAY['legal','ownership']),

('energy certificate','certificado de eficiencia energética',
 'An official document rating a property''s energy performance from A (best) to G (worst).',
 'Documento oficial que califica la eficiencia energética de una propiedad de la A (mejor) a la G (peor).',
 'EN-er-jee ser-TIF-i-kit','/ˈɛnədʒi səˈtɪfɪkɪt/',
 'The property has an energy certificate rating of B, which is excellent.',
 'La propiedad tiene un certificado de eficiencia energética con calificación B, excelente.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['EPC','energy performance certificate'],ARRAY['sustainability','running costs','green building'],
 'EPC = Energy Performance Certificate es la denominación oficial en UK.',2,4,ARRAY['legal','sustainability','regulation']),

('notary','notario',
 'A public official who authenticates legal documents and oversees property transactions.',
 'Funcionario público que autentica documentos legales y supervisa las transacciones inmobiliarias.',
 'NOH-ta-ree','/ˈnəʊtəri/',
 'Both parties met at the notary''s office to sign the deed.',
 'Ambas partes se reunieron en la notaría para firmar la escritura.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['notary public','civil law notary'],ARRAY['deed','conveyancing','closing'],
 NULL,2,4,ARRAY['legal','professional']),

-- URBAN PLANNING
('cadastral value','valor catastral',
 'The official administrative value assigned to a property by the land registry.',
 'Valor administrativo oficial asignado a una propiedad por el catastro.',
 'ka-DAS-tral VAL-yoo','/kəˈdæstrəl ˈvæljuː/',
 'The cadastral value is used to calculate the annual property tax.',
 'El valor catastral se utiliza para calcular el impuesto anual sobre bienes inmuebles.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='urban-planning'),
 ARRAY['rateable value','assessed value'],ARRAY['property tax','cadastre','IBI'],
 NULL,4,3,ARRAY['legal','tax','spain']),

('property tax','impuesto sobre bienes inmuebles / IBI',
 'An annual tax levied by local authorities on property owners based on the property''s value.',
 'Impuesto anual que cobran las autoridades locales a los propietarios en función del valor del inmueble.',
 'PROP-er-tee TAKS','/ˈprɒpəti tæks/',
 'The annual property tax for the apartment is €800.',
 'El impuesto anual sobre bienes inmuebles del apartamento es de 800 €.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='urban-planning'),
 ARRAY['IBI','rates','council tax'],ARRAY['cadastral value','ownership','costs'],
 'En España se conoce como IBI; en UK "council tax".',2,4,ARRAY['tax','costs','ownership']),

('survey','inspección técnica',
 'A professional inspection of a property''s condition, structure and any defects.',
 'Inspección profesional del estado, estructura y posibles defectos de una propiedad.',
 'SER-vay','/ˈsɜːveɪ/',
 'The survey revealed damp problems in the basement.',
 'La inspección técnica reveló problemas de humedad en el sótano.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='legal'),
 ARRAY['property survey','structural survey','inspection'],ARRAY['surveyor','mortgage','valuation'],
 NULL,3,4,ARRAY['inspection','legal','british']),

-- INVESTMENT
('cash flow','flujo de caja',
 'The net income from a property after all expenses have been paid.',
 'Ingresos netos de una propiedad después de pagar todos los gastos.',
 'KASH FLOH','/kæʃ fləʊ/',
 'The property generates a positive cash flow of €500 per month.',
 'La propiedad genera un flujo de caja positivo de 500 € al mes.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['net income','income flow'],ARRAY['yield','rental income','expenses'],
 NULL,3,5,ARRAY['investment','finance','rental']),

('rental yield','rentabilidad por alquiler',
 'The annual rental income expressed as a percentage of the property value.',
 'Ingresos anuales del alquiler expresados como porcentaje del valor de la propiedad.',
 'REN-tal YEELD','/ˈrɛntəl jiːld/',
 'The property achieves a gross rental yield of 6.5% per year.',
 'La propiedad obtiene una rentabilidad bruta por alquiler del 6,5% anual.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['gross yield','net yield'],ARRAY['ROI','cash flow','investment'],
 'La rentabilidad bruta no descuenta gastos; la neta sí.',3,4,ARRAY['investment','rental','profitability']),

('capital appreciation','revalorización del capital',
 'An increase in the value of a property over time.',
 'Aumento del valor de una propiedad a lo largo del tiempo.',
 'KAP-i-tal a-pree-shee-AY-shun','/ˈkæpɪtəl əˌpriːʃiˈeɪʃən/',
 'The area has seen strong capital appreciation of 15% over three years.',
 'La zona ha experimentado una fuerte revalorización del 15% en tres años.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['appreciation','value growth','capital growth'],ARRAY['capital gain','ROI','market'],
 NULL,3,4,ARRAY['investment','value','long-term']),

('flip','compra-reforma-venta',
 'The strategy of buying a property, improving it quickly and reselling it for profit.',
 'Estrategia de comprar una propiedad, mejorarla rápidamente y revenderla con beneficio.',
 'FLIP','/flɪp/',
 'They flipped the house in four months, making a profit of €25,000.',
 'Vendieron la casa en cuatro meses tras la reforma, obteniendo un beneficio de 25.000 €.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['house flip','buy-renovate-sell'],ARRAY['renovation','profit','investment strategy'],
 NULL,3,3,ARRAY['investment','strategy','renovation']),

('net operating income','ingresos operativos netos',
 'The gross rental income minus all operating expenses, excluding mortgage payments.',
 'Ingresos brutos del alquiler menos todos los gastos operativos, sin incluir la hipoteca.',
 'NET OP-er-ay-ting IN-kum','/nɛt ˈɒpəreɪtɪŋ ˈɪŋkʌm/',
 'The NOI of the building was €120,000 after deducting maintenance and management fees.',
 'El NOI del edificio fue de 120.000 € tras deducir mantenimiento y honorarios de gestión.',
 'C2',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['NOI','operating income'],ARRAY['cash flow','yield','ROI'],
 'Se abrevia NOI constantemente en análisis de inversión.',5,3,ARRAY['investment','finance','advanced']),

('portfolio','cartera de activos inmobiliarios',
 'A collection of properties owned by an investor or company.',
 'Conjunto de propiedades en propiedad de un inversor o empresa.',
 'port-FOH-lee-oh','/pɔːtˈfəʊliəʊ/',
 'The fund manages a portfolio of 120 residential properties across Spain.',
 'El fondo gestiona una cartera de 120 propiedades residenciales en España.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['property portfolio','real estate portfolio'],ARRAY['asset','investment','management'],
 NULL,3,4,ARRAY['investment','management']),

('gross rental yield','rentabilidad bruta por alquiler',
 'Annual rental income divided by property value, before deducting expenses.',
 'Ingresos anuales del alquiler divididos entre el valor del inmueble, antes de deducir gastos.',
 'GROHSS REN-tal YEELD','/ɡrəʊs ˈrɛntəl jiːld/',
 'A gross rental yield of 7% is considered attractive in most Spanish cities.',
 'Una rentabilidad bruta del 7% se considera atractiva en la mayoría de ciudades españolas.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['gross yield'],ARRAY['net rental yield','ROI','rental income'],
 NULL,3,3,ARRAY['investment','rental','calculation']),

('net rental yield','rentabilidad neta por alquiler',
 'Annual rental income minus all costs, divided by property value.',
 'Ingresos anuales del alquiler menos todos los costes, divididos entre el valor del inmueble.',
 'NET REN-tal YEELD','/nɛt ˈrɛntəl jiːld/',
 'After deducting taxes and maintenance, the net rental yield dropped to 4.2%.',
 'Tras deducir impuestos y mantenimiento, la rentabilidad neta cayó al 4,2%.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['net yield'],ARRAY['gross rental yield','ROI','expenses'],
 NULL,4,3,ARRAY['investment','rental','calculation']),

-- PROPERTY MANAGEMENT
('property manager','gestor / administrador de propiedades',
 'A person or company employed to oversee the day-to-day management of a rental property.',
 'Persona o empresa contratada para supervisar la gestión diaria de una propiedad en alquiler.',
 'PROP-er-tee MAN-a-jer','/ˈprɒpəti ˈmænɪdʒər/',
 'The property manager handled all tenant enquiries and maintenance issues.',
 'El gestor de propiedades atendió todas las consultas de los inquilinos e incidencias de mantenimiento.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['building manager','estate manager'],ARRAY['landlord','tenant','maintenance'],
 NULL,2,4,ARRAY['management','professional','rental']),

('community fees','gastos de comunidad',
 'Regular charges paid by property owners in a building for shared services and maintenance.',
 'Cuotas periódicas que pagan los propietarios de un edificio por servicios comunes y mantenimiento.',
 'ko-MYOO-ni-tee FEEZ','/kəˈmjuːnɪti fiːz/',
 'Community fees cover the cost of the lift, cleaning and garden maintenance.',
 'Los gastos de comunidad cubren el coste del ascensor, limpieza y mantenimiento del jardín.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['service charge','HOA fees','owners community'],ARRAY['homeowners association','maintenance','costs'],
 NULL,2,4,ARRAY['costs','management','spain']),

('homeowners association','comunidad de propietarios',
 'An organisation that manages shared areas and enforces rules in a residential development.',
 'Organización que gestiona las zonas comunes y aplica las normas en una comunidad residencial.',
 'HOME-oh-ners a-SO-shee-AY-shun','/ˈhəʊməʊnəz əˌsəʊsiˈeɪʃən/',
 'The homeowners association voted to repaint the building''s exterior.',
 'La comunidad de propietarios votó repintar la fachada del edificio.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['HOA','residents association'],ARRAY['community fees','maintenance','rules'],
 'Se abrevia HOA en mercados anglosajones.',3,4,ARRAY['management','community']),

-- MARKETING
('broker','agente / corredor',
 'A licensed professional who arranges property transactions between buyers and sellers.',
 'Profesional licenciado que organiza las transacciones inmobiliarias entre compradores y vendedores.',
 'BROH-ker','/ˈbrəʊkər/',
 'The broker negotiated a commission of 2% on the sale price.',
 'El agente negoció una comisión del 2% sobre el precio de venta.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['real estate agent','estate agent','realtor'],ARRAY['commission','listing','client'],
 'En EEUU "realtor" (con R mayúscula) es miembro de NAR.',2,5,ARRAY['professional','sales']),

('commission','comisión',
 'A fee paid to an agent or broker for completing a property transaction.',
 'Honorario pagado a un agente o intermediario por completar una transacción inmobiliaria.',
 'ko-MIH-shun','/kəˈmɪʃən/',
 'The standard commission in the area is 3% of the sale price.',
 'La comisión estándar en la zona es del 3% del precio de venta.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['fee','agency fee'],ARRAY['broker','agent','transaction'],
 NULL,2,5,ARRAY['finance','professional','sales']),

('open house','jornada de puertas abiertas',
 'A scheduled period when a property for sale is open for prospective buyers to view.',
 'Período programado en que una propiedad en venta está abierta para que los compradores potenciales puedan visitarla.',
 'OH-pen HOWS','/ˈəʊpən haʊs/',
 'The open house on Sunday attracted 15 potential buyers.',
 'La jornada de puertas abiertas del domingo atrajo a 15 compradores potenciales.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['show day','open viewing'],ARRAY['listing','viewing','lead'],
 NULL,2,4,ARRAY['marketing','sales-process']),

('MLS','sistema de listado múltiple',
 'Multiple Listing Service: a shared database of properties listed for sale by agents.',
 'Servicio de listado múltiple: base de datos compartida de propiedades en venta entre agentes.',
 'em-el-ES','/ˌem ˌel ˈes/',
 'The property was added to the MLS within 24 hours of the listing agreement.',
 'La propiedad se añadió al MLS en 24 horas desde el contrato de exclusiva.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['multiple listing service','shared listing'],ARRAY['listing','broker','portal'],
 'Más utilizado en EEUU; en España la colaboración entre agencias es similar.',3,3,ARRAY['american','marketing','technology']),

-- ARCHITECTURE
('apartment','apartamento / piso',
 'A set of rooms for living in that is part of a larger building.',
 'Conjunto de habitaciones para vivir que forma parte de un edificio mayor.',
 'a-PART-ment','/əˈpɑːtmənt/',
 'The apartment on the fourth floor has stunning views of the city.',
 'El piso del cuarto piso tiene unas vistas impresionantes de la ciudad.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['flat','unit'],ARRAY['building','floor','lease'],
 '"Flat" es el término británico; "apartment" es más americano.',1,5,ARRAY['basic','residential']),

('studio apartment','estudio',
 'A small self-contained apartment with a single main room serving as living area and bedroom.',
 'Pequeño apartamento con una sola estancia principal que sirve como sala de estar y dormitorio.',
 'STOO-dee-oh a-PART-ment','/ˈstjuːdiəʊ əˈpɑːtmənt/',
 'Studio apartments are popular with young professionals in the city centre.',
 'Los estudios son populares entre los jóvenes profesionales en el centro de la ciudad.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['studio flat','bedsit','efficiency apartment'],ARRAY['apartment','bachelor pad','open plan'],
 NULL,1,4,ARRAY['residential','small','type']),

('penthouse','ático',
 'A luxurious apartment on the top floor of a building, often with a terrace.',
 'Apartamento lujoso en el último piso de un edificio, a menudo con terraza.',
 'PENT-hows','/ˈpɛnthaʊs/',
 'The penthouse offers panoramic views and a private rooftop pool.',
 'El ático ofrece vistas panorámicas y una piscina privada en la azotea.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='luxury'),
 ARRAY['top floor apartment','sky home'],ARRAY['apartment','luxury','terrace'],
 NULL,2,4,ARRAY['luxury','residential','top-floor']),

('duplex','dúplex',
 'A residential property on two floors connected by an internal staircase.',
 'Propiedad residencial en dos plantas conectadas por una escalera interior.',
 'DOO-pleks','/ˈdjuːplɛks/',
 'The duplex has an open-plan kitchen on the ground floor and bedrooms above.',
 'El dúplex tiene una cocina abierta en la planta baja y dormitorios arriba.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['maisonette','two-storey apartment'],ARRAY['apartment','floor','staircase'],
 NULL,2,3,ARRAY['residential','type','two-floor']),

('townhouse','casa adosada',
 'A house that is joined to the houses on either side, often spread over several floors.',
 'Casa que está unida a las casas de los lados, a menudo distribuida en varias plantas.',
 'TOWN-hows','/ˈtaʊnhaʊs/',
 'The townhouse has three floors and a private rear garden.',
 'La casa adosada tiene tres plantas y un jardín privado trasero.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['terraced house','row house'],ARRAY['semi-detached','detached','garden'],
 'Diferencia con "terraced house": todas las casas en hilera son terraced, mientras que townhouse puede referirse a una casa urbana de varias plantas.',2,4,ARRAY['residential','type']),

('villa','villa / chalet',
 'A large detached house, often luxury and in a warm climate, usually with a garden and pool.',
 'Casa grande independiente, a menudo de lujo y en clima cálido, generalmente con jardín y piscina.',
 'VIL-a','/ˈvɪlə/',
 'The villa in Marbella has six bedrooms and a 15-metre heated pool.',
 'La villa de Marbella tiene seis dormitorios y una piscina climatizada de 15 metros.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='luxury'),
 ARRAY['country house','detached house'],ARRAY['pool','garden','luxury'],
 NULL,1,4,ARRAY['luxury','residential','spanish-coast']),

('open plan','distribución abierta / diáfano',
 'A layout where different living areas are combined into one large space without dividing walls.',
 'Distribución donde diferentes zonas de vida se combinan en un espacio abierto sin tabiques.',
 'OH-pen PLAN','/ˈəʊpən plæn/',
 'The open plan kitchen and living room creates a bright, sociable space.',
 'La cocina y salón de distribución abierta crean un espacio luminoso y sociable.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['open concept','open layout'],ARRAY['floor plan','kitchen','living room'],
 NULL,2,4,ARRAY['design','layout','modern']),

('balcony','balcón',
 'A small platform projecting from the outside wall of a building with a railing.',
 'Pequeña plataforma que sobresale de la pared exterior de un edificio con barandilla.',
 'BAL-ko-nee','/ˈbælkəni/',
 'The apartment comes with a south-facing balcony overlooking the sea.',
 'El apartamento tiene un balcón orientado al sur con vistas al mar.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['terrace','outside space'],ARRAY['terrace','apartment','outdoor'],
 'Un balcón es más pequeño que una terraza.',1,4,ARRAY['outdoor','feature']),

('terrace','terraza',
 'A flat outdoor area attached to a property, larger than a balcony.',
 'Zona exterior plana adosada a una propiedad, más grande que un balcón.',
 'TER-is','/ˈtɛrəs/',
 'The penthouse has a 50 square metre south-facing terrace.',
 'El ático tiene una terraza de 50 metros cuadrados orientada al sur.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['roof terrace','patio','outdoor space'],ARRAY['balcony','garden','outdoor'],
 NULL,1,4,ARRAY['outdoor','feature','luxury']),

-- LUXURY
('swimming pool','piscina',
 'An artificial pool of water for swimming, a key luxury feature in residential properties.',
 'Estanque artificial de agua para natación, elemento clave de lujo en propiedades residenciales.',
 'SWIM-ing POOL','/ˈswɪmɪŋ puːl/',
 'The villa has a heated swimming pool and panoramic sea views.',
 'La villa tiene piscina climatizada y vistas panorámicas al mar.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='luxury'),
 ARRAY['pool'],ARRAY['villa','garden','luxury feature'],
 NULL,1,4,ARRAY['luxury','amenity','outdoor']),

('gated community','urbanización cerrada / residencial privado',
 'A residential area with controlled access, security and shared amenities.',
 'Zona residencial con acceso controlado, seguridad e instalaciones compartidas.',
 'GAY-ted ko-MYOO-ni-tee','/ˈɡeɪtɪd kəˈmjuːnɪti/',
 'The gated community offers 24-hour security and a private golf course.',
 'La urbanización cerrada ofrece seguridad 24 horas y campo de golf privado.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='luxury'),
 ARRAY['private residential','secure development'],ARRAY['security','amenities','luxury'],
 NULL,3,3,ARRAY['luxury','security','community']),

('concierge service','servicio de conserjería',
 'A premium property service providing personal assistance to residents or buyers.',
 'Servicio inmobiliario premium que proporciona asistencia personalizada a residentes o compradores.',
 'kon-see-ERZH SER-vis','/ˌkɒnsiˈeəʒ ˈsɜːvɪs/',
 'The concierge service arranges everything from restaurant bookings to dry cleaning.',
 'El servicio de conserjería gestiona desde reservas de restaurantes hasta tintorería.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='luxury'),
 ARRAY['concierge','butler service'],ARRAY['luxury','amenity','property management'],
 NULL,3,2,ARRAY['luxury','service','premium']),

-- COMMERCIAL
('commercial property','propiedad comercial',
 'Buildings or land used for business purposes rather than residential.',
 'Edificios o terrenos destinados a uso comercial y no residencial.',
 'ko-MER-shal PROP-er-tee','/kəˈmɜːʃəl ˈprɒpəti/',
 'The fund focuses on commercial property in city centre locations.',
 'El fondo se centra en propiedades comerciales en el centro de la ciudad.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='commercial'),
 ARRAY['commercial real estate','CRE'],ARRAY['office','retail','industrial'],
 NULL,2,4,ARRAY['commercial','investment']),

('retail space','local comercial',
 'A property unit designed for selling goods or services directly to consumers.',
 'Unidad inmobiliaria diseñada para vender bienes o servicios directamente al consumidor.',
 'REE-tayl SPAYS','/ˈriːteɪl speɪs/',
 'The retail space is located on the high street with heavy footfall.',
 'El local comercial está ubicado en la calle principal con mucho tránsito de clientes.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='commercial'),
 ARRAY['shop','storefront','commercial unit'],ARRAY['footfall','high street','lease'],
 NULL,2,3,ARRAY['commercial','retail']),

('office building','edificio de oficinas',
 'A building designed and used for business and administrative purposes.',
 'Edificio diseñado y utilizado para fines empresariales y administrativos.',
 'OF-is BIL-ding','/ˈɒfɪs ˈbɪldɪŋ/',
 'The office building has been fully refurbished and is ready for occupation.',
 'El edificio de oficinas ha sido completamente renovado y está listo para ocupar.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='commercial'),
 ARRAY['office block','business premises'],ARRAY['lease','tenant','commercial'],
 NULL,1,4,ARRAY['commercial','offices']),

('warehouse','almacén / nave industrial',
 'A large building used for storing goods or for light industrial activities.',
 'Gran edificio utilizado para almacenar mercancías o para actividades industriales ligeras.',
 'WAIR-hows','/ˈweəhaʊs/',
 'The company leased a 2,000 square metre warehouse on the industrial estate.',
 'La empresa arrendó una nave de 2.000 m² en el polígono industrial.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='commercial'),
 ARRAY['storage unit','industrial unit','shed'],ARRAY['logistics','industrial','lease'],
 NULL,2,3,ARRAY['commercial','industrial','logistics']),

-- PROPTECH
('smart home','hogar inteligente / domótica',
 'A property equipped with technology that allows remote control of systems and appliances.',
 'Propiedad equipada con tecnología que permite controlar de forma remota sistemas y electrodomésticos.',
 'SMART HOHM','/smɑːt həʊm/',
 'The smart home system controls heating, lighting and security from a single app.',
 'El sistema domótico controla la calefacción, iluminación y seguridad desde una sola app.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='proptech'),
 ARRAY['connected home','automated home','domotics'],ARRAY['technology','energy','security'],
 NULL,2,3,ARRAY['technology','modern','feature']),

('virtual tour','visita virtual',
 'A digital simulation of a property that allows online viewing using photos or video.',
 'Simulación digital de una propiedad que permite visitarla online mediante fotos o vídeo.',
 'VER-choo-al TUR','/ˈvɜːtʃuəl tʊər/',
 'The virtual tour generated 200 online viewings in the first 48 hours.',
 'La visita virtual generó 200 visitas online en las primeras 48 horas.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='proptech'),
 ARRAY['3D tour','online viewing','360 tour'],ARRAY['listing','photography','marketing'],
 NULL,2,4,ARRAY['technology','marketing','digital']),

('CRM','CRM / sistema de gestión de clientes',
 'Customer Relationship Management: software used to manage client interactions and leads.',
 'Gestión de relaciones con clientes: software para gestionar interacciones con clientes y contactos.',
 'SEE-ar-EM','/ˌsiː ɑː ˈɛm/',
 'The agency uses a CRM to track every lead from first contact to closing.',
 'La agencia usa un CRM para seguir cada contacto desde el primer contacto hasta el cierre.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='proptech'),
 ARRAY['client management software','lead management'],ARRAY['lead','follow-up','pipeline'],
 NULL,2,4,ARRAY['technology','sales','management']),

-- HOSPITALITY
('short-term rental','alquiler vacacional / alquiler de corta duración',
 'A property rented out for short periods, typically for tourism or business travel.',
 'Propiedad alquilada por periodos cortos, típicamente para turismo o viajes de negocios.',
 'SHORT-term REN-tal','/ʃɔːt tɜːm ˈrɛntəl/',
 'Short-term rental platforms have transformed the holiday accommodation market.',
 'Las plataformas de alquiler vacacional han transformado el mercado de alojamiento turístico.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='hospitality'),
 ARRAY['vacation rental','holiday let','STR'],ARRAY['Airbnb','tourism','regulation'],
 NULL,2,4,ARRAY['rental','tourism','hospitality']),

('occupancy rate','tasa de ocupación',
 'The percentage of available rental units that are currently occupied.',
 'Porcentaje de unidades de alquiler disponibles que están actualmente ocupadas.',
 'OK-yoo-pan-see RAYT','/ˈɒkjʊpənsi reɪt/',
 'The hotel achieved a 92% occupancy rate during the summer months.',
 'El hotel logró una tasa de ocupación del 92% durante los meses de verano.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='hospitality'),
 ARRAY['occupancy','fill rate'],ARRAY['vacancy','revenue','performance'],
 NULL,3,3,ARRAY['hospitality','investment','management']),

-- Additional terms to reach 100+
('asking price','precio de salida / precio de venta',
 'The price at which a property is initially offered for sale.',
 'Precio al que se ofrece inicialmente una propiedad para la venta.',
 'AS-king PRYS','/ˈɑːskɪŋ praɪs/',
 'The asking price was €250,000, but the property sold for €235,000.',
 'El precio de salida era de 250.000 €, pero la propiedad se vendió por 235.000 €.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['list price','guide price','advertised price'],ARRAY['offer','negotiation','valuation'],
 NULL,2,5,ARRAY['price','sales','negotiation']),

('estate agent','agente inmobiliario',
 'A person or business that arranges the buying, selling or renting of properties.',
 'Persona o empresa que gestiona la compraventa o alquiler de propiedades.',
 'ih-STATE AY-jent','/ɪˈsteɪt ˈeɪdʒənt/',
 'The estate agent organised three viewings and received two offers within a week.',
 'El agente inmobiliario organizó tres visitas y recibió dos ofertas en una semana.',
 'A2',(SELECT id FROM lexestate_categories WHERE slug='sales'),
 ARRAY['realtor','broker','property agent'],ARRAY['commission','listing','client'],
 '"Estate agent" es el término británico; "realtor" o "real estate agent" son americanos.',1,5,ARRAY['professional','british','sales']),

('market value','valor de mercado',
 'The estimated price a property would achieve if sold in current market conditions.',
 'Precio estimado que alcanzaría una propiedad si se vendiera en las condiciones actuales del mercado.',
 'MAR-ket VAL-yoo','/ˈmɑːkɪt ˈvæljuː/',
 'The surveyor confirmed the market value was 10% above the asking price.',
 'El tasador confirmó que el valor de mercado era un 10% superior al precio de salida.',
 'B1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['fair market value','current value'],ARRAY['valuation','appraisal','asking price'],
 NULL,2,5,ARRAY['finance','valuation','price']),

('service charge','gastos de servicio',
 'A regular payment made by leaseholders for the maintenance of shared areas in a building.',
 'Pago periódico realizado por los titulares del arrendamiento para el mantenimiento de zonas comunes.',
 'SER-vis CHARJ','/ˈsɜːvɪs tʃɑːdʒ/',
 'The annual service charge covers the lifts, concierge and communal garden.',
 'El coste anual de servicio cubre los ascensores, la conserjería y el jardín comunal.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['maintenance charge','management fee'],ARRAY['leasehold','community fees','landlord'],
 NULL,3,3,ARRAY['british','costs','leasehold']),

('planning permission','licencia urbanística',
 'Official approval from a local authority to carry out building work or change land use.',
 'Aprobación oficial de una autoridad local para realizar obras de construcción o cambiar el uso del suelo.',
 'PLAN-ing per-MI-shun','/ˈplænɪŋ pəˈmɪʃən/',
 'Planning permission was granted for the extension after a three-month review.',
 'La licencia urbanística fue concedida para la ampliación tras una revisión de tres meses.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='urban-planning'),
 ARRAY['building permit','development consent'],ARRAY['zoning','council','architect'],
 NULL,3,4,ARRAY['legal','planning','british']),

('depreciation','depreciación',
 'The reduction in the value of a property or asset over time due to wear, age or market conditions.',
 'Reducción del valor de una propiedad o activo a lo largo del tiempo por desgaste, edad o condiciones de mercado.',
 'dee-pree-shee-AY-shun','/dɪˌpriːʃiˈeɪʃən/',
 'Tax depreciation on commercial properties can reduce the investor''s taxable income.',
 'La depreciación fiscal de las propiedades comerciales puede reducir los ingresos imponibles del inversor.',
 'C1',(SELECT id FROM lexestate_categories WHERE slug='finance'),
 ARRAY['value decrease','write-down'],ARRAY['appreciation','tax','investment'],
 NULL,4,3,ARRAY['finance','tax','investment']),

('square metre','metro cuadrado',
 'The standard unit of measurement for property floor area in Europe.',
 'Unidad estándar de medición de la superficie de una propiedad en Europa.',
 'SKWAIR MEE-ter','/skweər ˈmiːtər/',
 'The apartment measures 75 square metres and has two bedrooms.',
 'El apartamento mide 75 metros cuadrados y tiene dos dormitorios.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['sq m','m²'],ARRAY['floor plan','built area','usable area'],
 'En EEUU se usan square feet (sq ft): 1 m² ≈ 10.76 sq ft.',1,5,ARRAY['measurement','basic']),

('garage','garaje',
 'A building or space within a building used for storing one or more vehicles.',
 'Edificio o espacio dentro de un edificio destinado a guardar uno o más vehículos.',
 'ga-RAHJ','/ˈɡærɑːʒ/',
 'The property includes a private garage with space for two cars.',
 'La propiedad incluye un garaje privado con espacio para dos coches.',
 'A1',(SELECT id FROM lexestate_categories WHERE slug='architecture'),
 ARRAY['parking','car space'],ARRAY['parking space','building','property feature'],
 NULL,1,4,ARRAY['feature','parking','residential']),

('asset','activo',
 'Anything of value that can be owned, including property, which generates income or appreciates.',
 'Cualquier cosa de valor que puede poseerse, incluida la propiedad, que genera ingresos o se revaloriza.',
 'AS-et','/ˈæsɛt/',
 'Real estate is considered a stable long-term asset in any investment portfolio.',
 'Los bienes raíces se consideran un activo estable a largo plazo en cualquier cartera de inversión.',
 'B2',(SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['investment','property holding'],ARRAY['portfolio','liability','investment'],
 NULL,3,4,ARRAY['investment','finance'])
;

-- ─── Seed: Practice Questions ──────────────────────────────────────────────────
INSERT INTO lexestate_practice_questions
  (term_id, category_id, level, question_type, question_text, correct_answer, options, explanation)
SELECT
  t.id,
  t.category_id,
  t.level,
  'definition_es_to_word',
  t.definition_es,
  t.word_en,
  jsonb_build_array(
    t.word_en,
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1)
  ),
  'Translate this Spanish definition to find the English real estate term.'
FROM lexestate_terms t
WHERE t.frequency >= 4
LIMIT 30;

INSERT INTO lexestate_practice_questions
  (term_id, category_id, level, question_type, question_text, correct_answer, options, explanation)
SELECT
  t.id,
  t.category_id,
  t.level,
  'word_to_translation_es',
  'What is the Spanish translation of "' || t.word_en || '"?',
  t.translation_es,
  jsonb_build_array(
    t.translation_es,
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1)
  ),
  'Choose the correct Spanish translation for this real estate term.'
FROM lexestate_terms t
WHERE t.frequency >= 4
LIMIT 30;
