-- migrations/011_lexestate_vocabulary.sql
-- Primera carga de vocabulario: 100 términos inmobiliarios en inglés
-- Fuente: 2026-06-27_vocabulario_inmobiliario_ingles.xlsx (Grupo Ansan)

-- ─── Limpiar datos de seed anteriores ────────────────────────────────────────
DELETE FROM lexestate_practice_questions;
DELETE FROM lexestate_review_history;
DELETE FROM lexestate_user_progress;
DELETE FROM lexestate_favorites;
DELETE FROM lexestate_terms;
DELETE FROM lexestate_categories;

-- ─── Categorías (15) ──────────────────────────────────────────────────────────
INSERT INTO lexestate_categories (name, slug, description, icon) VALUES
('Property Types',             'property-types',          'Types of real estate properties and ownership structures',  '🏠'),
('Transactions',               'transactions',            'Buying, selling and property transfer processes',           '🤝'),
('Financing',                  'financing',               'Mortgages, loans and property financing',                   '🏦'),
('Valuation',                  'valuation',               'Property assessment, appraisal and value metrics',          '📊'),
('Leasing & Rental',           'leasing-rental',          'Rental contracts, landlords, tenants and leases',           '🔑'),
('Agents & Professionals',     'agents-professionals',    'Real estate professionals and their roles',                 '👔'),
('Market & Analysis',          'market-analysis',         'Market conditions, data and price analysis',               '📈'),
('Legal & Documentation',      'legal-documentation',     'Legal documents, registry and official processes',          '⚖️'),
('Taxes & Costs',              'taxes-costs',             'Taxes, fees and transaction costs in property',             '💶'),
('Development & Construction', 'development-construction','New builds, renovation and construction terms',             '🏗️'),
('Investment',                 'investment',              'Property investment strategies and returns',                '📈'),
('Location & Description',     'location-description',   'Location features and property descriptions',              '📍'),
('Property Management',        'property-management',     'Managing properties, costs and communities',               '🏢'),
('Marketing',                  'marketing',               'Listing, presenting and marketing properties',             '📣'),
('Luxury & Premium',           'luxury-premium',          'High-end and luxury real estate vocabulary',               '✨');

-- ─── Términos (100) ──────────────────────────────────────────────────────────
INSERT INTO lexestate_terms
  (word_en, translation_es, definition_en, definition_es, ipa,
   example_en, example_es, level, category_id, synonyms, difficulty, frequency, tags)
VALUES

-- ── Property Types (8) ──
('Real Estate',
 'bienes raíces / sector inmobiliario',
 'Property consisting of land and buildings on it, including its natural resources.',
 'Bienes inmuebles que incluyen el terreno, las edificaciones y los recursos naturales asociados.',
 '/ˌriːəl ɪˈsteɪt/',
 'He invested his savings in real estate rather than the stock market.',
 'Invirtió sus ahorros en bienes raíces en lugar de en la bolsa.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['property','realty','immovable property'], 2, 4, ARRAY['types','classification']),

('Residential Property',
 'propiedad residencial / vivienda',
 'Property used for housing purposes, such as apartments, houses, or condominiums.',
 'Inmueble destinado a uso habitacional: pisos, casas, chalets o apartamentos.',
 '/ˌrezɪˈdenʃəl ˈprɒpəti/',
 'The developer specializes in residential property in the coastal areas of Málaga.',
 'La promotora se especializa en vivienda residencial en las zonas costeras de Málaga.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['housing','dwelling','home'], 2, 4, ARRAY['types','classification']),

('Commercial Property',
 'propiedad comercial',
 'Real estate used for business activities, including offices, retail spaces, hotels, and restaurants.',
 'Inmueble destinado a actividades empresariales: oficinas, locales comerciales, hoteles y restaurantes.',
 '/kəˈmɜːʃəl ˈprɒpəti/',
 'The agency manages a portfolio of commercial properties throughout the city centre.',
 'La agencia gestiona una cartera de inmuebles comerciales por todo el centro de la ciudad.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['business property','commercial real estate'], 2, 4, ARRAY['types','classification']),

('Industrial Property',
 'propiedad industrial / nave industrial',
 'Real estate used for manufacturing, warehousing, logistics, or industrial activities.',
 'Inmueble destinado a producción, almacenamiento, logística o actividades industriales.',
 '/ɪnˈdʌstriəl ˈprɒpəti/',
 'The logistics company is looking for industrial property near the motorway.',
 'La empresa logística busca nave industrial cerca de la autovía.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['industrial estate','warehouse','manufacturing facility'], 3, 3, ARRAY['types','classification']),

('Mixed-use Development',
 'desarrollo de uso mixto',
 'A development that combines residential, commercial, and sometimes industrial uses within a single project or building.',
 'Desarrollo que combina usos residencial, comercial y a veces industrial en un mismo proyecto o edificio.',
 '/ˌmɪkst juːz dɪˈveləpmənt/',
 'The mixed-use development includes ground-floor retail, offices on levels 1–3, and apartments above.',
 'El desarrollo de uso mixto incluye comercios en planta baja, oficinas en las plantas 1–3 y viviendas en las superiores.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['multi-use building','integrated development'], 4, 2, ARRAY['types','classification']),

('Freehold',
 'pleno dominio / propiedad absoluta',
 'Permanent and absolute ownership of property and the land it stands on, with no time limit.',
 'Propiedad plena y absoluta del inmueble y del suelo sobre el que se asienta, sin límite temporal. Equivalente a la plena propiedad en España.',
 '/ˈfriːhəʊld/',
 'They purchased the building as freehold, giving them full control over the asset.',
 'Adquirieron el edificio en plena propiedad, lo que les otorga control total sobre el activo.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['full ownership','outright ownership'], 4, 2, ARRAY['types','legal']),

('Leasehold',
 'arrendamiento de largo plazo',
 'The right to use and occupy a property for a fixed period under the terms of a lease, without owning the land.',
 'Derecho a usar y ocupar un inmueble durante un período fijo según los términos de un contrato de arrendamiento, sin poseer el terreno.',
 '/ˈliːshəʊld/',
 'The apartment is sold as leasehold with 99 years remaining on the lease.',
 'El apartamento se vende en régimen de arrendamiento con 99 años restantes de contrato.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['leasehold interest','tenancy'], 4, 2, ARRAY['types','legal']),

('Off-plan Property',
 'propiedad sobre plano',
 'A property purchased before or during its construction, based on architectural plans and developer specifications.',
 'Inmueble adquirido antes o durante su construcción, basándose en planos y especificaciones del promotor. Equivale a vivienda sobre plano.',
 '/ˌɒf ˈplæn ˈprɒpəti/',
 'Buying off-plan can offer discounts but also carries construction risk.',
 'Comprar sobre plano puede ofrecer descuentos, pero también conlleva riesgo de construcción.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='property-types'),
 ARRAY['pre-construction property','under-construction unit'], 3, 3, ARRAY['types','development']),

-- ── Transactions (8) ──
('Conveyancing',
 'transmisión inmobiliaria / compraventa legal',
 'The legal process of transferring ownership of property from seller to buyer.',
 'Proceso jurídico de transferencia de la propiedad de un inmueble del vendedor al comprador. Incluye escrituras, notaría y registro.',
 '/kənˈveɪənsɪŋ/',
 'The conveyancing process in Spain involves a notary and registration at the Land Registry.',
 'El proceso de transmisión de propiedad en España requiere notario e inscripción en el Registro de la Propiedad.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['property transfer','title transfer'], 4, 2, ARRAY['transaction','process']),

('Closing',
 'cierre / firma ante notario',
 'The final step in a real estate transaction where documents are signed, funds are transferred, and ownership passes to the buyer.',
 'Fase final de una transacción inmobiliaria en la que se firman los documentos, se transfieren los fondos y la propiedad pasa al comprador. Equivale a la firma de la escritura ante notario.',
 '/ˈkləʊzɪŋ/',
 'The closing is scheduled for next Friday at the notary''s office.',
 'El cierre está previsto para el próximo viernes en la notaría.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['settlement','completion','signing'], 3, 3, ARRAY['transaction','process']),

('Earnest Money',
 'arras / señal',
 'A deposit made by a buyer to demonstrate serious intent to purchase a property, typically held in escrow until closing.',
 'Depósito realizado por el comprador para demostrar su intención real de adquirir el inmueble. Equivale a las arras o señal en España.',
 '/ˈɜːnɪst ˈmʌni/',
 'The buyers put down €10,000 in earnest money to secure the property.',
 'Los compradores entregaron 10.000 € en concepto de arras para reservar el inmueble.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['deposit','good faith deposit','arras'], 3, 3, ARRAY['transaction','finance']),

('Escrow',
 'depósito en garantía',
 'An arrangement where a third party holds funds or documents until the conditions of a transaction are fulfilled.',
 'Acuerdo por el que un tercero custodia fondos o documentos hasta que se cumplen las condiciones de una transacción. Similar al depósito en garantía.',
 '/ˈeskrəʊ/',
 'The deposit is held in escrow by the solicitor until completion.',
 'El depósito está en custodia del abogado hasta la firma final.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['trust account','held in trust'], 4, 2, ARRAY['transaction','finance']),

('Due Diligence',
 'diligencia debida',
 'A comprehensive investigation and verification of a property''s legal, physical, financial, and technical status before purchase.',
 'Investigación exhaustiva del estado legal, físico, financiero y técnico de un inmueble antes de su compra. Diligencia debida.',
 '/djuː ˈdɪlɪdʒəns/',
 'The investor conducted thorough due diligence before committing to the acquisition.',
 'El inversor realizó una exhaustiva diligencia debida antes de comprometerse con la adquisición.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['property investigation','legal check'], 4, 2, ARRAY['transaction','legal']),

('Listing',
 'anuncio / listado inmobiliario',
 'An agreement between a property owner and an agent to market and sell or rent the property, or the advertisement itself.',
 'Acuerdo entre el propietario y el agente para comercializar el inmueble, o el propio anuncio publicado en portales inmobiliarios.',
 '/ˈlɪstɪŋ/',
 'The listing showed attractive photos and a detailed floor plan of the apartment.',
 'El anuncio mostraba fotos atractivas y una planta detallada del apartamento.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['property listing','advertisement','portal ad'], 2, 4, ARRAY['transaction','marketing']),

('Counter Offer',
 'contraoferta',
 'A response to an offer in which new terms are proposed, rejecting the original offer.',
 'Respuesta a una oferta en la que se proponen nuevas condiciones, rechazando la propuesta original. Contraoferta.',
 '/ˈkaʊntər ˈɒfə/',
 'The seller made a counter offer of €350,000 after the buyer offered €330,000.',
 'El vendedor realizó una contraoferta de 350.000 € después de que el comprador ofreciera 330.000 €.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['counterbid','counterproposal'], 3, 3, ARRAY['transaction','negotiation']),

('Purchase Agreement',
 'contrato de compraventa',
 'A legally binding contract between buyer and seller detailing the terms and conditions of a property sale.',
 'Contrato vinculante entre comprador y vendedor que detalla los términos y condiciones de la venta del inmueble. Contrato de compraventa.',
 '/ˈpɜːtʃɪs əˈɡriːmənt/',
 'Both parties signed the purchase agreement before proceeding to the notary.',
 'Ambas partes firmaron el contrato de compraventa antes de acudir a la notaría.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='transactions'),
 ARRAY['sales contract','sale agreement','contrato de compraventa'], 3, 3, ARRAY['transaction','legal']),

-- ── Financing (9) ──
('Mortgage',
 'hipoteca',
 'A loan secured against real property, repaid in regular instalments over an agreed period with interest.',
 'Préstamo garantizado con un bien inmueble, devuelto en cuotas periódicas durante un plazo acordado con intereses. Hipoteca.',
 '/ˈmɔːɡɪdʒ/',
 'They took out a 25-year mortgage at a fixed rate of 2.5%.',
 'Contrataron una hipoteca a 25 años con un tipo fijo del 2,5%.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['home loan','property loan','hipoteca'], 2, 4, ARRAY['finance','mortgage']),

('Loan-to-Value (LTV)',
 'ratio préstamo-valor (LTV)',
 'The ratio of a mortgage loan to the appraised value of the property, expressed as a percentage.',
 'Porcentaje que representa el importe del préstamo respecto al valor de tasación del inmueble. Ratio préstamo-valor (LTV).',
 '/ləʊn tə ˈvæljuː/',
 'With a 20% deposit, the LTV is 80%, which usually secures better interest rates.',
 'Con un 20% de entrada, el LTV es del 80%, lo que suele garantizar mejores tipos de interés.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['LTV ratio','mortgage ratio'], 4, 2, ARRAY['finance','mortgage']),

('Down Payment',
 'entrada / pago inicial',
 'The initial upfront payment made by the buyer when purchasing a property, representing a percentage of the total price.',
 'Pago inicial que realiza el comprador al adquirir un inmueble, que representa un porcentaje del precio total. Entrada o señal inicial.',
 '/daʊn ˈpeɪmənt/',
 'Banks in Spain typically require a minimum down payment of 20% for residential purchases.',
 'Los bancos en España suelen exigir una entrada mínima del 20% para compras residenciales.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['deposit','initial payment','entrada'], 2, 4, ARRAY['finance','mortgage']),

('Amortisation',
 'amortización',
 'The gradual repayment of a loan through regular scheduled payments of principal and interest over its term.',
 'Devolución gradual de un préstamo mediante pagos periódicos de capital e intereses durante su plazo. Amortización.',
 '/əˌmɔːtɪˈzeɪʃən/',
 'A French amortisation schedule means constant monthly payments throughout the loan term.',
 'Un cuadro de amortización francés implica cuotas mensuales constantes durante toda la vida del préstamo.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['loan repayment','debt amortization'], 4, 2, ARRAY['finance','mortgage']),

('Fixed-rate Mortgage',
 'hipoteca a tipo fijo',
 'A mortgage with an interest rate that remains unchanged for the entire loan term, offering payment predictability.',
 'Hipoteca cuyo tipo de interés no varía durante toda la vida del préstamo, aportando estabilidad en las cuotas. Hipoteca a tipo fijo.',
 '/ˈfɪkst reɪt ˈmɔːɡɪdʒ/',
 'With rising Euribor rates, many buyers opted for a fixed-rate mortgage for security.',
 'Con la subida del Euríbor, muchos compradores optaron por una hipoteca a tipo fijo por seguridad.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['fixed mortgage','tipo fijo'], 3, 3, ARRAY['finance','mortgage']),

('Variable-rate Mortgage',
 'hipoteca a tipo variable',
 'A mortgage with an interest rate that fluctuates periodically based on a benchmark index such as Euribor.',
 'Hipoteca cuyo tipo de interés varía periódicamente según un índice de referencia como el Euríbor. Hipoteca a tipo variable.',
 '/ˈveəriəbl reɪt ˈmɔːɡɪdʒ/',
 'The variable-rate mortgage started at Euribor + 0.8%, making it competitive initially.',
 'La hipoteca variable comenzó en Euríbor + 0,8%, lo que la hacía competitiva inicialmente.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['adjustable-rate mortgage','ARM','tipo variable'], 3, 3, ARRAY['finance','mortgage']),

('Euribor',
 'Euríbor',
 'Euro Interbank Offered Rate; the benchmark interest rate used across the Eurozone, widely used as the reference for variable-rate mortgages in Spain.',
 'Euro Interbank Offered Rate; tipo de interés de referencia en la zona euro, ampliamente utilizado como índice para las hipotecas variables en España.',
 '/ˈjʊərɪbɔː/',
 'The 12-month Euribor reached its highest level in 15 years in 2023.',
 'El Euríbor a 12 meses alcanzó su nivel más alto en 15 años en 2023.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['interbank rate','reference rate'], 4, 2, ARRAY['finance','mortgage']),

('Bridging Loan',
 'préstamo puente',
 'A short-term loan used to bridge the financial gap between buying a new property and selling an existing one.',
 'Préstamo a corto plazo utilizado para cubrir la brecha financiera entre la compra de un nuevo inmueble y la venta del existente. Préstamo puente.',
 '/ˈbrɪdʒɪŋ ləʊn/',
 'They used a bridging loan to secure the new apartment while their house was still on the market.',
 'Utilizaron un préstamo puente para asegurar el nuevo apartamento mientras su casa seguía en el mercado.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['bridge loan','interim loan','préstamo puente'], 4, 2, ARRAY['finance','mortgage']),

('Subrogation',
 'subrogación hipotecaria',
 'The transfer of a mortgage from one lender to another, or from the developer to the buyer, without modifying the loan terms.',
 'Transferencia de una hipoteca de un prestamista a otro, o del promotor al comprador, sin modificar las condiciones del préstamo. Subrogación.',
 '/ˌsʌbrəˈɡeɪʃən/',
 'By accepting subrogation of the developer''s mortgage, the buyer saved on arrangement fees.',
 'Al aceptar la subrogación de la hipoteca del promotor, el comprador ahorró en gastos de constitución.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='financing'),
 ARRAY['mortgage transfer','loan subrogation'], 4, 2, ARRAY['finance','mortgage']),

-- ── Valuation (7) ──
('Appraisal',
 'tasación',
 'A professional assessment of a property''s market value conducted by a certified appraiser or valuer.',
 'Evaluación profesional del valor de mercado de un inmueble realizada por un tasador homologado. Tasación.',
 '/əˈpreɪzəl/',
 'The bank requires an independent appraisal before approving the mortgage.',
 'El banco exige una tasación independiente antes de aprobar la hipoteca.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['valuation','property assessment','tasación'], 3, 3, ARRAY['finance','valuation']),

('Market Value',
 'valor de mercado',
 'The estimated price at which a property would sell in a competitive, open market between a willing buyer and a willing seller.',
 'Precio estimado al que se vendería un inmueble en un mercado abierto y competitivo entre un comprador y vendedor dispuestos. Valor de mercado.',
 '/ˈmɑːkɪt ˈvæljuː/',
 'The market value of the property increased by 12% following the infrastructure improvements.',
 'El valor de mercado del inmueble aumentó un 12% tras las mejoras de infraestructura.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['fair market value','open market value'], 3, 3, ARRAY['finance','valuation']),

('Comparable Sales (Comps)',
 'comparables / testigos de mercado',
 'Recently sold properties similar in size, location, and condition used as reference points to determine a property''s market value.',
 'Inmuebles vendidos recientemente de características similares usados como referencia para valorar un inmueble. Comparables o testigos.',
 '/kəmˈpærəbl seɪlz/',
 'The valuer analysed six comparable sales in the same neighbourhood to determine the price.',
 'El tasador analizó seis ventas comparables en el mismo barrio para determinar el precio.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['comps','comparables','market comparisons'], 4, 2, ARRAY['finance','valuation']),

('Gross Development Value (GDV)',
 'valor de desarrollo bruto (GDV)',
 'The total estimated value of a development project once all units are completed and sold at market prices.',
 'Valor total estimado de un proyecto de promoción una vez que todas las unidades están completadas y vendidas a precios de mercado.',
 '/ɡrəʊs dɪˈveləpmənt ˈvæljuː/',
 'The GDV of the new development is projected at €45 million based on current market prices.',
 'El valor de venta total de la nueva promoción se proyecta en 45 millones de euros según los precios de mercado actuales.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['GDV','end value','development value'], 4, 2, ARRAY['finance','valuation']),

('Yield',
 'rentabilidad / rendimiento',
 'The annual income generated by a property expressed as a percentage of its purchase price or market value.',
 'Renta anual generada por un inmueble expresada como porcentaje de su precio de compra o valor de mercado. Rentabilidad bruta.',
 '/jiːld/',
 'The apartment delivers a gross yield of 5.5% based on the current rental income.',
 'El apartamento ofrece una rentabilidad bruta del 5,5% basada en los ingresos actuales del alquiler.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['rental yield','return','rentabilidad'], 4, 2, ARRAY['finance','valuation']),

('Capitalization Rate (Cap Rate)',
 'tasa de capitalización (cap rate)',
 'The ratio of a property''s net operating income to its current market value, used to assess investment return.',
 'Ratio entre los ingresos netos de explotación de un inmueble y su valor de mercado, utilizado para evaluar la rentabilidad de la inversión.',
 '/ˌkæpɪtəlaɪˈzeɪʃən reɪt/',
 'A cap rate of 6% is considered attractive for commercial property in secondary Spanish cities.',
 'Una tasa de capitalización del 6% se considera atractiva para el inmobiliario comercial en ciudades secundarias españolas.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['cap rate','capitalisation rate','tasa de capitalización'], 4, 2, ARRAY['finance','valuation']),

('Net Operating Income (NOI)',
 'ingresos netos de explotación (NOI)',
 'The annual income generated by a property after deducting operating expenses, before mortgage payments and taxes.',
 'Ingresos anuales generados por un inmueble tras deducir los gastos de explotación, antes de pagos hipotecarios e impuestos.',
 '/net ˈɒpəreɪtɪŋ ˈɪŋkʌm/',
 'The NOI of the office building is €280,000 per year after maintenance and management costs.',
 'Los ingresos netos de explotación del edificio de oficinas son 280.000 € anuales tras los costes de mantenimiento y gestión.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='valuation'),
 ARRAY['NOI','net income','operating profit'], 4, 2, ARRAY['finance','valuation']),

-- ── Leasing & Rental (8) ──
('Lease',
 'arrendamiento / contrato de alquiler',
 'A legally binding contract granting the right to use a property for a specified period in exchange for rent.',
 'Contrato jurídicamente vinculante que otorga el derecho a usar un inmueble durante un período determinado a cambio de una renta. Arrendamiento o contrato de alquiler.',
 '/liːs/',
 'The commercial lease runs for five years with a break clause at year three.',
 'El arrendamiento comercial tiene una duración de cinco años con una cláusula de rescisión al tercer año.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['tenancy agreement','rental contract','arrendamiento'], 2, 4, ARRAY['rental','contract']),

('Landlord',
 'arrendador / propietario arrendador',
 'The owner of a property who rents it to a tenant under a lease or rental agreement.',
 'Propietario de un inmueble que lo arrienda a un inquilino mediante un contrato de alquiler. Arrendador o casero.',
 '/ˈlændlɔːd/',
 'The landlord is responsible for major repairs and structural maintenance.',
 'El arrendador es responsable de las reparaciones importantes y del mantenimiento estructural.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['lessor','property owner','arrendador'], 2, 4, ARRAY['rental','role']),

('Tenant',
 'arrendatario / inquilino',
 'A person or entity that occupies and pays rent for a property owned by another party.',
 'Persona o entidad que ocupa y paga renta por un inmueble propiedad de otra parte. Arrendatario o inquilino.',
 '/ˈtenənt/',
 'The commercial tenant signed a five-year lease for the ground-floor retail unit.',
 'El arrendatario comercial firmó un contrato de cinco años para el local de planta baja.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['lessee','renter','occupier','arrendatario'], 2, 4, ARRAY['rental','role']),

('Security Deposit',
 'fianza / depósito de garantía',
 'A sum of money paid by a tenant before occupancy, held by the landlord as security against damages or unpaid rent.',
 'Suma de dinero pagada por el inquilino antes de la ocupación, retenida por el arrendador como garantía frente a daños o impagos. Fianza o depósito de garantía.',
 '/sɪˈkjʊərɪti dɪˈpɒzɪt/',
 'Spanish law requires a security deposit of one month''s rent for residential tenancies.',
 'La ley española exige una fianza de un mes de renta para los arrendamientos de vivienda.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['rental deposit','fianza','guarantee deposit'], 2, 4, ARRAY['rental','finance']),

('Rent Review',
 'revisión de renta',
 'A clause in a commercial lease providing for periodic reassessment of the rent to reflect market conditions.',
 'Cláusula en un arrendamiento comercial que prevé la revisión periódica de la renta para reflejar las condiciones del mercado. Revisión de renta.',
 '/rent rɪˈvjuː/',
 'The rent review is carried out every three years based on the CPI index.',
 'La revisión de renta se realiza cada tres años en función del índice IPC.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['rental review','rent revision','revisión de renta'], 4, 2, ARRAY['rental','contract']),

('Gross Lease',
 'arrendamiento bruto',
 'A lease where the tenant pays a flat rent and the landlord covers all property operating expenses including taxes and insurance.',
 'Arrendamiento en el que el inquilino paga una renta fija y el arrendador asume todos los gastos de explotación incluyendo impuestos y seguros.',
 '/ɡrəʊs liːs/',
 'Under a gross lease, the landlord bears all operational costs of the property.',
 'En un arrendamiento bruto, el arrendador asume todos los costes operativos del inmueble.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['full-service lease'], 4, 2, ARRAY['rental','contract']),

('Net Lease',
 'arrendamiento neto',
 'A lease where the tenant pays rent plus some or all of the property''s operating expenses, such as taxes, insurance, and maintenance.',
 'Arrendamiento en el que el inquilino paga la renta más algunos o todos los gastos operativos del inmueble: impuestos, seguros y mantenimiento.',
 '/net liːs/',
 'In a triple net lease, the tenant covers taxes, insurance, and maintenance costs.',
 'En un arrendamiento triple neto, el inquilino cubre impuestos, seguros y costes de mantenimiento.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['NNN lease','triple net','net rent'], 4, 2, ARRAY['rental','contract']),

('Vacancy Rate',
 'tasa de desocupación / tasa de vacío',
 'The percentage of all available rental units in a property or market that are unoccupied at a given time.',
 'Porcentaje de unidades disponibles en un inmueble o mercado que están desocupadas en un momento determinado. Tasa de desocupación o vacío.',
 '/ˈveɪkənsi reɪt/',
 'The office vacancy rate in Málaga city centre fell to 4% in Q3.',
 'La tasa de desocupación de oficinas en el centro de Málaga bajó al 4% en el tercer trimestre.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='leasing-rental'),
 ARRAY['void rate','empty rate','tasa de vacío'], 4, 2, ARRAY['rental','market']),

-- ── Agents & Professionals (7) ──
('Real Estate Agent',
 'agente inmobiliario',
 'A licensed professional who represents buyers or sellers in real estate transactions, earning a commission.',
 'Profesional habilitado que representa a compradores o vendedores en transacciones inmobiliarias, percibiendo una comisión. Agente inmobiliario.',
 '/ˌriːəl ɪˈsteɪt ˈeɪdʒənt/',
 'The real estate agent negotiated a price reduction of €15,000 for her client.',
 'El agente inmobiliario negoció una reducción de precio de 15.000 € para su cliente.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['property agent','estate agent','realtor','agente inmobiliario'], 2, 4, ARRAY['professional','role']),

('Listing Agent',
 'agente del vendedor',
 'The real estate agent who represents the seller and is responsible for marketing the property.',
 'El agente inmobiliario que representa al vendedor y es responsable de la comercialización del inmueble. Agente vendedor.',
 '/ˈlɪstɪŋ ˈeɪdʒənt/',
 'The listing agent prepared a compelling marketing pack with professional photography.',
 'El agente vendedor preparó un dosier de marketing con fotografía profesional.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['seller''s agent','selling agent'], 3, 3, ARRAY['professional','role']),

('Buyer''s Agent',
 'agente del comprador',
 'A real estate agent who exclusively represents the buyer''s interests during a property purchase.',
 'Agente inmobiliario que representa exclusivamente los intereses del comprador durante la adquisición de un inmueble. Agente del comprador.',
 '/ˈbaɪərz ˈeɪdʒənt/',
 'Hiring a buyer''s agent ensures unbiased advice and representation throughout the purchase.',
 'Contratar un agente del comprador garantiza asesoramiento imparcial y representación durante toda la compra.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['purchasing agent','buyer''s representative'], 3, 3, ARRAY['professional','role']),

('Broker',
 'corredor / intermediario inmobiliario',
 'A licensed professional who facilitates real estate transactions, often supervising agents and holding a higher-level licence.',
 'Profesional licenciado que facilita transacciones inmobiliarias, supervisando a menudo a otros agentes con una licencia de nivel superior. Corredor o intermediario.',
 '/ˈbrəʊkə/',
 'The mortgage broker found a competitive loan product suited to the client''s profile.',
 'El intermediario hipotecario encontró un producto de préstamo competitivo adaptado al perfil del cliente.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['intermediary','dealer','corredor'], 3, 3, ARRAY['professional','role']),

('Property Manager',
 'administrador de fincas / property manager',
 'A professional responsible for the day-to-day operations of a rental property on behalf of the owner.',
 'Profesional responsable de las operaciones diarias de un inmueble en alquiler en nombre del propietario. Administrador de fincas o property manager.',
 '/ˈprɒpəti ˈmænɪdʒə/',
 'The property manager handles tenant relations, maintenance, and monthly rent collection.',
 'El administrador de fincas gestiona las relaciones con inquilinos, el mantenimiento y la recaudación mensual de rentas.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['building manager','estate manager','administrador de fincas'], 3, 3, ARRAY['professional','role']),

('Developer',
 'promotor / promotora inmobiliaria',
 'A company or individual that finances and oversees the construction of new properties or the renovation of existing ones.',
 'Empresa o individuo que financia y supervisa la construcción de nuevos inmuebles o la renovación de existentes. Promotor o promotora inmobiliaria.',
 '/dɪˈveləpə/',
 'The developer launched the new residential scheme at the Málaga property fair.',
 'La promotora presentó la nueva promoción residencial en el salón inmobiliario de Málaga.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['property developer','housebuilder','promotor'], 2, 4, ARRAY['professional','role']),

('Surveyor',
 'perito / tasador técnico',
 'A qualified professional who inspects buildings and land to assess their condition, value, or boundaries.',
 'Profesional cualificado que inspecciona edificios y terrenos para evaluar su estado, valor o linderos. Perito o tasador técnico.',
 '/səˈveɪə/',
 'The surveyor identified damp problems and roof defects in the pre-purchase inspection.',
 'El perito identificó problemas de humedad y defectos en la cubierta durante la inspección previa a la compra.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='agents-professionals'),
 ARRAY['building inspector','chartered surveyor','perito'], 3, 3, ARRAY['professional','role']),

-- ── Market & Analysis (6) ──
('Buyer''s Market',
 'mercado de compradores',
 'A market condition where supply exceeds demand, giving buyers negotiating power and leading to lower prices.',
 'Condición de mercado en la que la oferta supera a la demanda, dando poder de negociación a los compradores y tendiendo a bajar los precios. Mercado de compradores.',
 '/ˈbaɪərz ˈmɑːkɪt/',
 'In a buyer''s market, properties stay longer on the market and sellers accept lower offers.',
 'En un mercado de compradores, los inmuebles permanecen más tiempo en el mercado y los vendedores aceptan ofertas más bajas.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['soft market','oversupplied market'], 3, 3, ARRAY['market','analysis']),

('Seller''s Market',
 'mercado de vendedores',
 'A market condition where demand exceeds supply, giving sellers negotiating power and driving prices upward.',
 'Condición de mercado en la que la demanda supera la oferta, dando poder de negociación a los vendedores y empujando los precios al alza. Mercado de vendedores.',
 '/ˈseləz ˈmɑːkɪt/',
 'The Costa del Sol is currently a strong seller''s market due to high foreign demand.',
 'La Costa del Sol es actualmente un fuerte mercado de vendedores debido a la alta demanda extranjera.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['hot market','undersupplied market'], 3, 3, ARRAY['market','analysis']),

('Absorption Rate',
 'tasa de absorción',
 'The rate at which available properties in a market are sold or leased during a given period, indicating supply-demand balance.',
 'Velocidad a la que los inmuebles disponibles en un mercado se venden o arriendan durante un período determinado, indicando el equilibrio oferta-demanda. Tasa de absorción.',
 '/əbˈzɔːpʃən reɪt/',
 'An absorption rate of 15 units per month suggests strong demand in the new development.',
 'Una tasa de absorción de 15 unidades al mes indica una demanda fuerte en la nueva promoción.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['take-up rate','sales velocity','ritmo de ventas'], 4, 2, ARRAY['market','analysis']),

('Price per Square Metre',
 'precio por metro cuadrado',
 'A standardised measure of property value calculated by dividing the total price by the property''s total area in square metres.',
 'Medida estandarizada del valor de un inmueble calculada dividiendo el precio total entre la superficie en metros cuadrados. Precio por metro cuadrado.',
 '/praɪs pə ˈskweə ˈmiːtə/',
 'New-build apartments in central Málaga average €4,500 per square metre.',
 'Los apartamentos de obra nueva en el centro de Málaga promedian 4.500 € por metro cuadrado.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['price per sqm','€/m²','cost per square metre'], 2, 4, ARRAY['market','analysis']),

('Market Report',
 'informe de mercado',
 'A document analysing current real estate market conditions, including prices, trends, supply, and demand in a specific area.',
 'Documento que analiza las condiciones actuales del mercado inmobiliario, incluyendo precios, tendencias, oferta y demanda en un área específica. Informe de mercado.',
 '/ˈmɑːkɪt rɪˈpɔːt/',
 'The quarterly market report showed a 7% annual price increase in the luxury segment.',
 'El informe de mercado trimestral mostró un incremento anual del 7% en el segmento de lujo.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['market analysis','property report','informe de mercado'], 2, 4, ARRAY['market','analysis']),

('Supply and Demand',
 'oferta y demanda',
 'The economic relationship between the availability of properties (supply) and the desire to purchase or rent them (demand).',
 'Relación económica entre la disponibilidad de inmuebles (oferta) y el deseo de comprarlos o arrendarlos (demanda). Oferta y demanda.',
 '/səˈplaɪ ənd dɪˈmɑːnd/',
 'Restricted supply and growing demand continue to push prices upward in prime locations.',
 'La oferta restringida y la creciente demanda continúan impulsando los precios al alza en ubicaciones prime.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='market-analysis'),
 ARRAY['oferta y demanda','market dynamics'], 2, 4, ARRAY['market','analysis']),

-- ── Legal & Documentation (7) ──
('Title Deed',
 'escritura de propiedad',
 'A legal document that serves as evidence of a person''s right to ownership of a property.',
 'Documento legal que acredita el derecho de una persona sobre la propiedad de un inmueble. Escritura de propiedad o de compraventa.',
 '/ˈtaɪtl diːd/',
 'The title deed must be registered at the Land Registry to secure the buyer''s ownership.',
 'La escritura de propiedad debe inscribirse en el Registro de la Propiedad para garantizar la titularidad del comprador.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['property deed','escritura','deed of sale'], 3, 3, ARRAY['legal','documentation']),

('Land Registry',
 'Registro de la Propiedad',
 'The official government register that records ownership, charges, and encumbrances on land and property.',
 'Registro público oficial que recoge la titularidad, cargas y gravámenes sobre terrenos e inmuebles. Registro de la Propiedad.',
 '/lænd ˈredʒɪstri/',
 'A Land Registry search confirms the seller is the legal owner and there are no outstanding charges.',
 'Una nota simple del Registro de la Propiedad confirma que el vendedor es el propietario legal y que no hay cargas pendientes.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['property register','Registro de la Propiedad','catastro'], 3, 3, ARRAY['legal','documentation']),

('Encumbrance',
 'carga / gravamen',
 'Any claim, lien, charge, or liability attached to a property that may limit its use or affect its title.',
 'Cualquier reclamación, hipoteca, carga o responsabilidad vinculada a un inmueble que puede limitar su uso o afectar a su titularidad. Carga o gravamen.',
 '/ɪnˈkʌmbrəns/',
 'The property was sold subject to an encumbrance of an existing mortgage that needed to be cancelled.',
 'El inmueble se vendió sujeto a una carga por una hipoteca existente que debía cancelarse.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['lien','charge','burden','carga','gravamen'], 4, 2, ARRAY['legal','documentation']),

('Planning Permission',
 'licencia de obras / permiso de construcción',
 'Official government authorisation required to construct, extend, or change the use of a building or land.',
 'Autorización oficial del gobierno necesaria para construir, ampliar o cambiar el uso de un edificio o terreno. Licencia de obras o permiso de construcción.',
 '/ˈplænɪŋ pəˈmɪʃən/',
 'The development cannot proceed until planning permission is granted by the municipality.',
 'La promoción no puede avanzar hasta que el ayuntamiento conceda la licencia de obras.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['building permit','licencia de obras','planning consent'], 3, 3, ARRAY['legal','documentation']),

('Certificate of Occupancy',
 'cédula de habitabilidad / licencia de primera ocupación',
 'An official document certifying that a building complies with applicable regulations and is suitable for habitation or use.',
 'Documento oficial que certifica que un edificio cumple la normativa aplicable y es apto para ser habitado o utilizado. Cédula de habitabilidad o licencia de primera ocupación.',
 '/səˈtɪfɪkɪt əv ˈɒkjʊpənsi/',
 'The buyers will not receive keys until the certificate of occupancy is issued by the town hall.',
 'Los compradores no recibirán las llaves hasta que el ayuntamiento emita la licencia de primera ocupación.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['habitation certificate','cédula de habitabilidad','licencia de primera ocupación'], 3, 3, ARRAY['legal','documentation']),

('Power of Attorney',
 'poder notarial',
 'A legal document authorising one person to act on behalf of another in legal and financial matters, including property transactions.',
 'Documento legal que autoriza a una persona a actuar en nombre de otra en asuntos legales y financieros, incluidas transacciones inmobiliarias. Poder notarial.',
 '/ˈpaʊər əv əˈtɜːni/',
 'The overseas investor granted power of attorney to their solicitor to sign the deed on their behalf.',
 'El inversor extranjero otorgó un poder notarial a su abogado para que firmara la escritura en su nombre.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['POA','legal proxy','poder notarial'], 4, 2, ARRAY['legal','documentation']),

('NIE Number',
 'NIE (Número de Identificación de Extranjero)',
 'Número de Identificación de Extranjero; the tax identification number required by foreigners to conduct legal and financial activities in Spain, including property purchases.',
 'Número de Identificación de Extranjero; número de identificación fiscal obligatorio para que los extranjeros realicen actividades legales y financieras en España, incluida la compra de inmuebles.',
 '/ˌen aɪ ˈiː ˈnʌmbə/',
 'Foreign buyers must obtain an NIE number before completing any property transaction in Spain.',
 'Los compradores extranjeros deben obtener el NIE antes de completar cualquier transacción inmobiliaria en España.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='legal-documentation'),
 ARRAY['foreign tax ID','número de extranjero'], 3, 3, ARRAY['legal','spain']),

-- ── Taxes & Costs (7) ──
('Stamp Duty',
 'AJD / impuesto de actos jurídicos documentados',
 'A government tax levied on property transactions and certain legal documents. In Spain, it refers broadly to AJD and ITP.',
 'Impuesto gubernamental sobre transacciones inmobiliarias y ciertos documentos legales. En España equivale al AJD (Actos Jurídicos Documentados) y al ITP (Impuesto de Transmisiones Patrimoniales).',
 '/stæmp ˈdjuːti/',
 'Stamp duty on new-build properties in Andalusia is currently set at 1.2% of the purchase price.',
 'El AJD para obra nueva en Andalucía es actualmente del 1,2% del precio de compra.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['AJD','document tax','transfer tax'], 3, 3, ARRAY['tax','costs']),

('Transfer Tax (ITP)',
 'ITP (Impuesto de Transmisiones Patrimoniales)',
 'A tax paid on the purchase of second-hand residential properties. In Andalusia, the ITP rate is 7% of the purchase price.',
 'Impuesto que se abona en la compra de inmuebles residenciales de segunda mano. En Andalucía, el tipo del ITP es del 7% del precio de compra.',
 '/ˈtrænsfɜː tæks/',
 'The transfer tax on the resale apartment amounted to €21,000 at 7% of the sale price.',
 'El ITP del apartamento de segunda mano ascendió a 21.000 € al 7% del precio de venta.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['ITP','property transfer tax','impuesto de transmisiones'], 4, 2, ARRAY['tax','costs']),

('VAT (Value Added Tax)',
 'IVA (Impuesto sobre el Valor Añadido)',
 'A consumption tax applied to new-build residential properties. In Spain, the standard rate for residential property is 10% (IVA).',
 'Impuesto al consumo aplicado a los inmuebles residenciales de obra nueva. En España, el tipo general para vivienda residencial es del 10% (IVA).',
 '/viː eɪ tiː/',
 'New-build residential properties in Spain are subject to 10% VAT (IVA), while commercial properties pay 21%.',
 'Las viviendas de obra nueva en España están sujetas al 10% de IVA, mientras que los inmuebles comerciales tributan al 21%.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['IVA','sales tax','goods and services tax'], 3, 3, ARRAY['tax','costs']),

('Capital Gains Tax',
 'impuesto sobre ganancias patrimoniales',
 'A tax levied on the profit made from selling a property, calculated as the difference between the sale price and the original purchase price.',
 'Impuesto sobre el beneficio obtenido de la venta de un inmueble, calculado como la diferencia entre el precio de venta y el precio de compra original. Impuesto sobre la ganancia patrimonial.',
 '/ˈkæpɪtl ɡeɪnz tæks/',
 'Non-residents selling property in Spain are subject to a 19% capital gains tax on their profit.',
 'Los no residentes que venden inmuebles en España están sujetos a un 19% de impuesto sobre la ganancia patrimonial.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['CGT','plusvalía estatal','ganancia patrimonial'], 4, 2, ARRAY['tax','costs']),

('Property Tax (IBI)',
 'IBI (Impuesto sobre Bienes Inmuebles)',
 'An annual municipal tax on property owners based on the cadastral value of the property. Known in Spain as IBI (Impuesto sobre Bienes Inmuebles).',
 'Impuesto municipal anual sobre los propietarios de inmuebles basado en el valor catastral. En España se conoce como IBI (Impuesto sobre Bienes Inmuebles).',
 '/ˈprɒpəti tæks/',
 'The annual IBI for the villa in Marbella is €3,200, payable to the local council.',
 'El IBI anual de la villa en Marbella es de 3.200 €, pagadero al ayuntamiento.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['IBI','council tax','municipal tax','rates'], 2, 4, ARRAY['tax','costs']),

('Plusvalía Municipal',
 'plusvalía municipal (IIVTNU)',
 'A Spanish municipal tax charged on the increase in urban land value between acquisition and sale, payable by the seller.',
 'Impuesto municipal español sobre el incremento del valor del suelo urbano entre la adquisición y la venta, pagadero por el vendedor. IIVTNU.',
 '/plʊsvaˈlia muniθiˈpal/',
 'The seller must pay the plusvalía municipal within 30 days of completing the sale.',
 'El vendedor debe pagar la plusvalía municipal en los 30 días siguientes a la escritura de compraventa.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['IIVTNU','land value increment tax','municipal land tax'], 4, 2, ARRAY['tax','costs','spain']),

('Notary Fees',
 'aranceles notariales',
 'The professional fees charged by a notary public for witnessing and formalising a property transaction.',
 'Honorarios del notario por la formalización de la escritura pública en una transacción inmobiliaria. Aranceles notariales.',
 '/ˈnəʊtəri fiːz/',
 'Notary fees for the purchase of a €300,000 property in Spain typically range from €600 to €1,200.',
 'Los aranceles notariales para la compra de un inmueble de 300.000 € en España oscilan normalmente entre 600 y 1.200 €.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='taxes-costs'),
 ARRAY['notarial fees','escritura costs','aranceles notariales'], 3, 3, ARRAY['tax','costs']),

-- ── Development & Construction (7) ──
('New Build',
 'obra nueva',
 'A newly constructed property that has never been lived in or occupied.',
 'Inmueble de nueva construcción que nunca ha sido habitado u ocupado. Obra nueva.',
 '/njuː bɪld/',
 'New-build properties benefit from a 10-year structural defect warranty in Spain.',
 'Los inmuebles de obra nueva se benefician de una garantía decenal por defectos estructurales en España.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['obra nueva','new construction','new development'], 2, 4, ARRAY['construction','development']),

('Renovation',
 'reforma / rehabilitación',
 'The process of improving or updating an existing property through repairs, upgrades, or remodelling.',
 'Proceso de mejora o actualización de un inmueble existente mediante reparaciones, actualizaciones o remodelaciones. Reforma o rehabilitación.',
 '/ˌrenəˈveɪʃən/',
 'The property required a full renovation, including new electrical wiring and kitchen fittings.',
 'El inmueble requería una reforma integral, incluyendo nueva instalación eléctrica y cocina nueva.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['refurbishment','remodelling','reforma','rehabilitación'], 2, 4, ARRAY['construction','development']),

('Floor Plan',
 'plano de planta / distribución',
 'A scale diagram showing the layout and dimensions of a property''s rooms and spaces as viewed from above.',
 'Diagrama a escala que muestra la distribución y dimensiones de las habitaciones y espacios de un inmueble visto desde arriba. Plano o distribución.',
 '/flɔː plæn/',
 'The floor plan shows an open-plan kitchen-living area of 45m² with three bedrooms.',
 'El plano muestra una zona de cocina-salón en planta abierta de 45 m² con tres dormitorios.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['layout','plan','plano de distribución'], 2, 4, ARRAY['construction','development']),

('Usable Area',
 'superficie útil',
 'The actual habitable floor space of a property, excluding walls, communal areas, and parking.',
 'Superficie habitable real de un inmueble, excluyendo muros, zonas comunes y aparcamiento. Superficie útil.',
 '/ˈjuːzəbl ˈeəriə/',
 'The apartment has a usable area of 85m² and a built area of 102m².',
 'El apartamento tiene una superficie útil de 85 m² y una superficie construida de 102 m².',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['net floor area','usable space','superficie útil'], 3, 3, ARRAY['construction','measurement']),

('Built Area',
 'superficie construida',
 'The total floor space of a property including walls, enclosed terraces, and a proportional share of communal areas.',
 'Superficie total de un inmueble incluyendo muros, terrazas cerradas y la parte proporcional de zonas comunes. Superficie construida.',
 '/bɪlt ˈeəriə/',
 'In Spain, properties are typically marketed using the built area, which is larger than the usable area.',
 'En España, los inmuebles se suelen comercializar con la superficie construida, que es mayor que la superficie útil.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['gross floor area','constructed area','superficie construida'], 3, 3, ARRAY['construction','measurement']),

('Cadastral Value',
 'valor catastral',
 'The official administrative value assigned to a property by the Spanish tax authority, used as the basis for calculating IBI and other taxes.',
 'Valor administrativo oficial asignado a un inmueble por la Dirección General del Catastro, usado como base para calcular el IBI y otros impuestos. Valor catastral.',
 '/kəˈdæstrəl ˈvæljuː/',
 'The cadastral value is usually significantly below the market value of the property.',
 'El valor catastral suele estar muy por debajo del valor de mercado del inmueble.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['rateable value','assessed value','valor catastral'], 4, 2, ARRAY['construction','tax']),

('Snag List',
 'lista de repasos / deficiencias',
 'A list of defects or unfinished items identified during a final inspection of a new-build property before handover.',
 'Lista de defectos o elementos inacabados identificados durante la inspección final de un inmueble de obra nueva antes de la entrega. Lista de repasos o de deficiencias.',
 '/snæɡ lɪst/',
 'The buyer submitted a snag list of 23 items to the developer before signing the handover certificate.',
 'El comprador entregó al promotor una lista de 23 repasos antes de firmar el acta de entrega.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='development-construction'),
 ARRAY['punch list','defect list','lista de repasos'], 3, 3, ARRAY['construction','development']),

-- ── Investment (6) ──
('Return on Investment (ROI)',
 'retorno sobre la inversión (ROI)',
 'A performance measure expressing the gain or loss from an investment relative to its cost, expressed as a percentage.',
 'Medida de rentabilidad que expresa la ganancia o pérdida de una inversión en relación con su coste, expresada como porcentaje. Retorno sobre la inversión.',
 '/rɪˈtɜːn ɒn ɪnˈvestmənt/',
 'The property investment delivered an ROI of 18% over five years including rental income and capital growth.',
 'La inversión inmobiliaria generó un ROI del 18% en cinco años, incluyendo ingresos por alquiler y revalorización.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['ROI','investment return','rentabilidad'], 4, 2, ARRAY['investment','finance']),

('Buy-to-Let',
 'compra para alquilar / buy-to-let',
 'The purchase of a property with the intention of renting it out to tenants rather than living in it.',
 'Compra de un inmueble con la intención de arrendarlo a inquilinos en lugar de habitarlo. Inversión para arrendamiento.',
 '/baɪ tə let/',
 'Buy-to-let investors in coastal areas can achieve strong yields through short-term holiday rentals.',
 'Los inversores para arrendamiento en zonas costeras pueden lograr buenas rentabilidades a través del alquiler vacacional.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['rental investment','investment property'], 3, 3, ARRAY['investment','rental']),

('Portfolio',
 'cartera inmobiliaria',
 'A collection of real estate assets held by an individual or company as part of an investment strategy.',
 'Conjunto de activos inmobiliarios en manos de un individuo o empresa como parte de una estrategia de inversión. Cartera inmobiliaria.',
 '/pɔːtˈfəʊliəʊ/',
 'The investment fund manages a diverse portfolio of residential, commercial, and logistics assets.',
 'El fondo de inversión gestiona una cartera diversificada de activos residenciales, comerciales y logísticos.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['property portfolio','asset portfolio','cartera'], 3, 3, ARRAY['investment','finance']),

('REIT (Real Estate Investment Trust)',
 'REIT / SOCIMI',
 'A company that owns, operates, or finances income-generating real estate, allowing investors to buy shares and receive dividends.',
 'Sociedad que posee, opera o financia inmuebles generadores de ingresos, permitiendo a los inversores comprar acciones y recibir dividendos. Equivalente español: SOCIMI.',
 '/riːt/',
 'Spanish REITs are known as SOCIMIs and are listed on the stock exchange.',
 'Los REIT españoles se denominan SOCIMIs y cotizan en bolsa.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['SOCIMI','property fund','listed property company'], 4, 2, ARRAY['investment','finance']),

('Leverage',
 'apalancamiento financiero',
 'The use of borrowed capital (mortgage) to increase the potential return on a real estate investment.',
 'Uso de capital prestado (hipoteca) para aumentar el retorno potencial de una inversión inmobiliaria. Apalancamiento financiero.',
 '/ˈliːvərɪdʒ/',
 'By using leverage, the investor controlled a €500,000 property with only €100,000 of own capital.',
 'Mediante el apalancamiento, el inversor controló un inmueble de 500.000 € con solo 100.000 € de capital propio.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['financial leverage','gearing','apalancamiento'], 4, 2, ARRAY['investment','finance']),

('Cash Flow',
 'flujo de caja',
 'The net income from a rental property after all operating expenses and mortgage payments have been deducted.',
 'Ingreso neto de un inmueble en alquiler después de deducir todos los gastos operativos y los pagos hipotecarios. Flujo de caja.',
 '/kæʃ fləʊ/',
 'The property generates a positive cash flow of €450 per month after all costs.',
 'El inmueble genera un flujo de caja positivo de 450 € al mes después de todos los costes.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='investment'),
 ARRAY['net income','cash return','flujo de caja'], 3, 3, ARRAY['investment','finance']),

-- ── Location & Description (6) ──
('Prime Location',
 'ubicación prime / zona premium',
 'A highly desirable location characterised by excellent accessibility, amenities, and prestige, commanding premium property prices.',
 'Ubicación muy deseable caracterizada por excelente accesibilidad, servicios y prestigio, que exige precios inmobiliarios superiores. Ubicación prime.',
 '/praɪm ləʊˈkeɪʃən/',
 'Properties in prime locations along the Golden Mile command prices above €10,000/m².',
 'Los inmuebles en ubicaciones prime a lo largo de la Milla de Oro alcanzan precios superiores a 10.000 €/m².',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['A-grade location','premium location','top location'], 3, 3, ARRAY['location','description']),

('Amenities',
 'dotaciones / servicios comunitarios',
 'Features and facilities that enhance the desirability and comfort of a property or its surroundings, such as pools, gyms, and concierge services.',
 'Características e instalaciones que aumentan el atractivo y confort de un inmueble o su entorno, como piscinas, gimnasios y servicios de conserjería. Servicios o instalaciones comunitarias.',
 '/əˈmiːnɪtiz/',
 'The residential complex offers amenities including a communal pool, gym, and landscaped gardens.',
 'El complejo residencial ofrece instalaciones que incluyen piscina comunitaria, gimnasio y jardines.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['facilities','features','dotaciones'], 2, 4, ARRAY['location','description']),

('Sea View',
 'vistas al mar',
 'A property feature offering direct or partial visual access to the sea from the property''s windows or terraces.',
 'Característica de un inmueble que ofrece acceso visual directo o parcial al mar desde sus ventanas o terrazas. Vistas al mar.',
 '/siː vjuː/',
 'The penthouse apartment boasts panoramic sea views from its wraparound terrace.',
 'El ático presume de vistas panorámicas al mar desde su terraza perimetral.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['ocean view','sea views','vistas al mar'], 2, 4, ARRAY['location','description']),

('Beachfront',
 'primera línea de playa',
 'A property located directly on or immediately adjacent to a beach, offering immediate beach access.',
 'Inmueble situado directamente en primera línea de playa o inmediatamente adyacente, con acceso directo a la playa. Primera línea de playa.',
 '/ˈbiːtʃfrʌnt/',
 'Beachfront properties in Marbella are among the most sought-after in the Mediterranean market.',
 'Los inmuebles en primera línea de playa en Marbella son de los más codiciados del mercado mediterráneo.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['oceanfront','seafront','primera línea de playa'], 2, 4, ARRAY['location','description']),

('Gated Community',
 'urbanización cerrada / privada',
 'A residential development with controlled access, perimeter security, and shared private amenities.',
 'Urbanización residencial con acceso controlado, seguridad perimetral e instalaciones privadas compartidas. Urbanización cerrada o privada.',
 '/ˈɡeɪtɪd kəˈmjuːnɪti/',
 'The gated community features 24-hour security, a golf course, and private clubhouse.',
 'La urbanización privada cuenta con seguridad 24 horas, campo de golf y club privado.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['private urbanisation','secure development','urbanización cerrada'], 3, 3, ARRAY['location','description']),

('Penthouse',
 'ático / penthouse',
 'A luxury apartment occupying the top floor of a building, typically featuring large terraces and premium views.',
 'Apartamento de lujo que ocupa la última planta de un edificio, generalmente con amplias terrazas y vistas privilegiadas. Ático o penthouse.',
 '/ˈpenthaʊs/',
 'The penthouse sold for €2.8 million, nearly double the price of the floors below.',
 'El ático se vendió por 2,8 millones de euros, casi el doble que las plantas inferiores.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='location-description'),
 ARRAY['top-floor apartment','ático','rooftop apartment'], 2, 4, ARRAY['location','description']),

-- ── Property Management (4) ──
('Homeowners Association (HOA)',
 'comunidad de propietarios (HOA)',
 'An organisation in a residential community that creates and enforces rules and manages communal areas and services.',
 'Organización en una comunidad residencial que establece y aplica normas y gestiona las zonas y servicios comunes. Comunidad de propietarios.',
 '/ˈhəʊməʊnəz əˌsəʊsiˈeɪʃən/',
 'The HOA collects monthly fees to maintain the communal gardens and swimming pool.',
 'La comunidad de propietarios recauda cuotas mensuales para mantener los jardines comunitarios y la piscina.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['residents'' association','comunidad de propietarios','strata'], 3, 3, ARRAY['management','costs']),

('Service Charge',
 'gastos de comunidad',
 'A regular fee paid by property owners to cover the cost of maintaining and managing communal areas and shared services.',
 'Cuota periódica pagada por los propietarios para cubrir los costes de mantenimiento y gestión de zonas comunes y servicios compartidos. Gastos de comunidad.',
 '/ˈsɜːvɪs tʃɑːdʒ/',
 'The monthly service charge of €180 covers cleaning, gardening, and lift maintenance.',
 'La cuota mensual de comunidad de 180 € cubre limpieza, jardinería y mantenimiento del ascensor.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['maintenance fee','community charge','gastos de comunidad'], 2, 4, ARRAY['management','costs']),

('Facilities Management',
 'gestión de instalaciones / facility management',
 'The professional coordination of all services and infrastructure needed to maintain and operate a building effectively.',
 'Coordinación profesional de todos los servicios e infraestructuras necesarios para mantener y operar un edificio de manera eficaz. Gestión de instalaciones o facility management.',
 '/fəˈsɪlɪtiz ˈmænɪdʒmənt/',
 'The building''s facilities management includes HVAC servicing, lift maintenance, and security.',
 'El facility management del edificio incluye el servicio de climatización, el mantenimiento de ascensores y la seguridad.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['FM','building management','facility management'], 4, 2, ARRAY['management','costs']),

('Depreciation',
 'depreciación / amortización fiscal',
 'The reduction in value of a property over time due to age, wear and tear, or obsolescence.',
 'Reducción del valor de un inmueble con el tiempo debido a la antigüedad, el desgaste o la obsolescencia. Depreciación o amortización fiscal.',
 '/dɪˌpriːʃiˈeɪʃən/',
 'Investors can claim depreciation as a tax deduction on investment properties.',
 'Los inversores pueden deducir la amortización fiscal del inmueble como gasto en la declaración de la renta.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='property-management'),
 ARRAY['amortisation','wear and tear','amortización fiscal'], 4, 2, ARRAY['management','tax']),

-- ── Marketing (5) ──
('Virtual Tour',
 'tour virtual / visita virtual 360°',
 'A digital simulation of a property that allows prospective buyers to explore it remotely using 360° photography or video.',
 'Simulación digital de un inmueble que permite a los potenciales compradores explorarlo de forma remota mediante fotografía o vídeo en 360°. Tour virtual.',
 '/ˈvɜːtʃuəl tʊə/',
 'The virtual tour allowed international buyers to view the property before travelling to Spain.',
 'El tour virtual permitió a los compradores internacionales ver el inmueble antes de viajar a España.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['3D tour','immersive tour','recorrido virtual'], 2, 4, ARRAY['marketing','sales']),

('Home Staging',
 'home staging / preparación del inmueble',
 'The process of preparing and presenting a property for sale in the most appealing way, often using professional furniture and décor.',
 'Proceso de preparación y presentación de un inmueble para la venta de la manera más atractiva posible, a menudo con muebles y decoración profesionales.',
 '/həʊm ˈsteɪdʒɪŋ/',
 'Professional home staging increased the property''s sale price by 8% compared to unstaged units.',
 'El home staging profesional aumentó el precio de venta del inmueble un 8% en comparación con unidades sin preparar.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['property staging','presentation','acondicionamiento'], 3, 3, ARRAY['marketing','sales']),

('Brochure',
 'dossier comercial / folleto de ventas',
 'A professionally designed printed or digital document marketing a property or development, containing images, plans, and specifications.',
 'Documento impreso o digital diseñado profesionalmente para comercializar un inmueble o promoción, con imágenes, planos y especificaciones. Dossier o folleto comercial.',
 '/ˈbrəʊʃə/',
 'The developer produced a luxury brochure for the new development at the international property fair.',
 'La promotora presentó un dossier de lujo de la nueva promoción en el salón inmobiliario internacional.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['property brochure','marketing pack','dossier comercial'], 2, 4, ARRAY['marketing','sales']),

('Lead',
 'lead / contacto comercial',
 'A prospective buyer or tenant who has expressed interest in a property and whose contact information has been captured.',
 'Potencial comprador o arrendatario que ha mostrado interés en un inmueble y del que se ha obtenido información de contacto. Lead o contacto comercial.',
 '/liːd/',
 'The portal campaign generated 45 qualified leads in the first month of marketing.',
 'La campaña en el portal generó 45 leads cualificados en el primer mes de comercialización.',
 'B1', (SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['prospect','enquiry','contacto','interesado'], 2, 4, ARRAY['marketing','sales']),

('CRM (Customer Relationship Management)',
 'CRM / gestor de relaciones con clientes',
 'A software system used by real estate professionals to manage interactions with clients, leads, and property listings.',
 'Sistema de software utilizado por los profesionales inmobiliarios para gestionar las interacciones con clientes, leads y listados de propiedades. CRM o gestor de relaciones con clientes.',
 '/siː ɑːr em/',
 'The team uses a CRM to track every lead from first contact through to completion.',
 'El equipo utiliza un CRM para seguir cada lead desde el primer contacto hasta el cierre de la operación.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='marketing'),
 ARRAY['client management software','property CRM'], 3, 3, ARRAY['marketing','sales']),

-- ── Luxury & Premium (5) ──
('Luxury Real Estate',
 'inmobiliario de lujo',
 'High-end property distinguished by exceptional quality, prestigious location, premium finishes, and exclusive amenities.',
 'Inmueble de alta gama caracterizado por calidad excepcional, ubicación de prestigio, acabados premium e instalaciones exclusivas. Inmobiliario de lujo.',
 '/ˈlʌkʃəri ˌriːəl ɪˈsteɪt/',
 'Marbella remains one of Europe''s top destinations for luxury real estate investment.',
 'Marbella sigue siendo uno de los principales destinos europeos para la inversión en inmobiliario de lujo.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='luxury-premium'),
 ARRAY['high-end property','premium real estate','inmobiliario de lujo'], 3, 3, ARRAY['luxury','premium']),

('Turnkey',
 'llave en mano',
 'A fully finished and equipped property that is ready for immediate occupation without any further work required.',
 'Inmueble completamente terminado y equipado, listo para su ocupación inmediata sin necesidad de obras adicionales. Llave en mano.',
 '/ˈtɜːnkiː/',
 'The developer offers a turnkey service including furniture packages and interior design.',
 'La promotora ofrece un servicio llave en mano que incluye paquetes de mobiliario y diseño de interiores.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='luxury-premium'),
 ARRAY['move-in ready','fully fitted','llave en mano'], 3, 3, ARRAY['luxury','premium']),

('Prime',
 'prime / primera calidad',
 'Describing a property, location, or asset of the highest quality and most desirable characteristics in the market.',
 'Describe un inmueble, ubicación o activo de la más alta calidad y características más deseables del mercado. Prime o de primera calidad.',
 '/praɪm/',
 'Prime coastal assets in the Costa del Sol continue to attract strong international demand.',
 'Los activos costeros prime en la Costa del Sol siguen atrayendo una fuerte demanda internacional.',
 'B2', (SELECT id FROM lexestate_categories WHERE slug='luxury-premium'),
 ARRAY['top-tier','premium','best-in-class'], 3, 3, ARRAY['luxury','premium']),

('Bespoke',
 'a medida / personalizado',
 'Custom-designed and built to the specific requirements and preferences of an individual client.',
 'Diseñado y construido a medida según los requisitos y preferencias específicos de un cliente. A medida o personalizado.',
 '/bɪˈspəʊk/',
 'The bespoke villa was designed by an award-winning architect to the client''s exact specifications.',
 'La villa a medida fue diseñada por un arquitecto de renombre siguiendo las especificaciones exactas del cliente.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='luxury-premium'),
 ARRAY['custom-built','tailor-made','made-to-order','a medida'], 4, 2, ARRAY['luxury','premium']),

('Trophy Asset',
 'activo trofeo',
 'An exceptionally prestigious and unique property that represents the pinnacle of a market segment, often with iconic status.',
 'Inmueble excepcionalmente prestigioso y único que representa la cima de un segmento de mercado, a menudo con estatus icónico. Activo trofeo.',
 '/ˈtrəʊfi ˈæset/',
 'The historic palace overlooking the bay was considered a true trophy asset by potential investors.',
 'El palacete histórico con vistas a la bahía era considerado un auténtico activo trofeo por los potenciales inversores.',
 'C1', (SELECT id FROM lexestate_categories WHERE slug='luxury-premium'),
 ARRAY['iconic property','flagship asset','activo de referencia'], 4, 2, ARRAY['luxury','premium']);

-- ─── Preguntas de práctica (auto-generadas) ──────────────────────────────────
INSERT INTO lexestate_practice_questions
  (term_id, category_id, level, question_type, question_text, correct_answer, options, explanation)
SELECT
  t.id, t.category_id, t.level,
  'definition_es_to_word',
  t.definition_es,
  t.word_en,
  jsonb_build_array(
    t.word_en,
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT word_en FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1)
  ),
  'Traduce esta definición en español para encontrar el término en inglés.'
FROM lexestate_terms t;

INSERT INTO lexestate_practice_questions
  (term_id, category_id, level, question_type, question_text, correct_answer, options, explanation)
SELECT
  t.id, t.category_id, t.level,
  'word_to_translation_es',
  'What is the Spanish equivalent of "' || t.word_en || '"?',
  t.translation_es,
  jsonb_build_array(
    t.translation_es,
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1),
    (SELECT translation_es FROM lexestate_terms WHERE id != t.id ORDER BY random() LIMIT 1)
  ),
  'Elige la traducción española correcta para este término inmobiliario.'
FROM lexestate_terms t;
